/**
 * add_moves_p2b.js — Phase 2 Batch B
 * Adds ~250 more moves (types: PSYCHIC, ROCK, GHOST, DRAGON, DARK, STEEL, FAIRY, BUG + extras)
 * Target: 713 + 250 = ~963 total
 */
const fs = require('fs');
const src = fs.readFileSync('./js/data/moves.js', 'utf8');
const existing = new Set([...src.matchAll(/^\s{2}([A-Z_0-9]+):\s*\{/gm)].map(m => m[1]).filter(id => id !== 'DG'));
console.log('Existing moves:', existing.size);

const newMoves = `
  // ═══════════════════════════════════════════════════════
  // PHASE 2 BATCH B — PSYCHIC (25 new)
  // ═══════════════════════════════════════════════════════
  MIND_CRUSH: { id:'MIND_CRUSH', name:'Mind Crush', type:'PSYCHIC', category:'SPECIAL', power:85, accuracy:100, pp:10, priority:0, animStyle:'PULSE',
    effect:{type:'STAT_LOWER',stat:'spDef',stages:1}, description:'Crushes the foe\'s mind, lowering Sp. Def.' },
  THOUGHT_WAVE: { id:'THOUGHT_WAVE', name:'Thought Wave', type:'PSYCHIC', category:'SPECIAL', power:70, accuracy:100, pp:15, priority:0, animStyle:'WAVE',
    effect:{type:'CONFUSE',chance:30}, description:'Invasive thoughts may confuse the foe.' },
  PSY_LANCE: { id:'PSY_LANCE', name:'Psy Lance', type:'PSYCHIC', category:'SPECIAL', power:80, accuracy:100, pp:10, priority:0, animStyle:'BEAM',
    effect:{type:'NONE'}, description:'A psychic lance of focused mental energy.' },
  COSMIC_STRIKE: { id:'COSMIC_STRIKE', name:'Cosmic Strike', type:'PSYCHIC', category:'SPECIAL', power:95, accuracy:90, pp:10, priority:0, animStyle:'BURST',
    effect:{type:'NONE'}, description:'Channels cosmic energy into a devastating strike.' },
  GRAVITY_PULSE: { id:'GRAVITY_PULSE', name:'Gravity Pulse', type:'PSYCHIC', category:'SPECIAL', power:75, accuracy:100, pp:15, priority:0, animStyle:'PULSE',
    effect:{type:'STAT_LOWER',stat:'spd',stages:1}, description:'A gravity wave slows the foe down.' },
  MIND_BARRIER: { id:'MIND_BARRIER', name:'Mind Barrier', type:'PSYCHIC', category:'STATUS', power:0, accuracy:100, pp:15, priority:0, animStyle:'SELF',
    effect:{type:'STAT_RAISE',stat:'spDef',stages:2}, description:'Erects a mental barrier, sharply raising Sp. Def.' },
  TELEKINETIC_SLAM: { id:'TELEKINETIC_SLAM', name:'Telekinetic Slam', type:'PSYCHIC', category:'SPECIAL', power:90, accuracy:95, pp:10, priority:0, animStyle:'SLAM',
    effect:{type:'NONE'}, description:'Lifts and slams the foe telekinetically.' },
  NEURAL_BLAST: { id:'NEURAL_BLAST', name:'Neural Blast', type:'PSYCHIC', category:'SPECIAL', power:80, accuracy:95, pp:10, priority:0, animStyle:'BURST',
    effect:{type:'PARALYSIS',chance:20}, description:'Fires a neural burst that may cause paralysis.' },
  ILLUSORY_STRIKE: { id:'ILLUSORY_STRIKE', name:'Illusory Strike', type:'PSYCHIC', category:'PHYSICAL', power:65, accuracy:100, pp:20, priority:0, animStyle:'MELEE',
    effect:{type:'CONFUSE',chance:20}, description:'Strikes with a phantom image that may confuse.' },
  DIMENSION_TEAR: { id:'DIMENSION_TEAR', name:'Dimension Tear', type:'PSYCHIC', category:'SPECIAL', power:110, accuracy:85, pp:8, priority:0, animStyle:'VORTEX',
    effect:{type:'NONE'}, description:'Tears a rift in space to unleash devastating energy.' },
  MINDSTORM: { id:'MINDSTORM', name:'Mindstorm', type:'PSYCHIC', category:'SPECIAL', power:75, accuracy:100, pp:15, priority:0, animStyle:'VORTEX',
    effect:{type:'CONFUSE',chance:50}, description:'A storm of psychic energy likely to confuse.' },
  PRECOGNITION: { id:'PRECOGNITION', name:'Precognition', type:'PSYCHIC', category:'STATUS', power:0, accuracy:100, pp:15, priority:0, animStyle:'SELF',
    effect:{type:'STAT_RAISE',stats:['spAtk','spd'],stages:1}, description:'Foresees the battle, raising Sp. Atk and Speed.' },
  PSYCHO_BURST: { id:'PSYCHO_BURST', name:'Psycho Burst', type:'PSYCHIC', category:'SPECIAL', power:100, accuracy:90, pp:10, priority:0, animStyle:'BURST',
    effect:{type:'STAT_LOWER',stat:'spDef',stages:1}, description:'A destructive psycho burst lowers Sp. Def.' },
  ASTRAL_PULSE: { id:'ASTRAL_PULSE', name:'Astral Pulse', type:'PSYCHIC', category:'SPECIAL', power:70, accuracy:100, pp:15, priority:0, animStyle:'PULSE',
    effect:{type:'NONE'}, description:'Pulses of astral energy ripple through the foe.' },
  MIND_MELD: { id:'MIND_MELD', name:'Mind Meld', type:'PSYCHIC', category:'STATUS', power:0, accuracy:100, pp:10, priority:0, animStyle:'AURA',
    effect:{type:'STAT_RAISE',stat:'spAtk',stages:3}, description:'Melds with the cosmos, sharply boosting Sp. Atk.' },
  WARP_BLAST: { id:'WARP_BLAST', name:'Warp Blast', type:'PSYCHIC', category:'SPECIAL', power:90, accuracy:100, pp:10, priority:0, animStyle:'BURST',
    effect:{type:'NONE'}, description:'Warps space to strike with distorted force.' },
  PRISM_BEAM: { id:'PRISM_BEAM', name:'Prism Beam', type:'PSYCHIC', category:'SPECIAL', power:80, accuracy:100, pp:10, priority:0, animStyle:'BEAM',
    effect:{type:'NONE'}, description:'Prismatic psychic light cuts through all defenses.' },
  MIRROR_MIND: { id:'MIRROR_MIND', name:'Mirror Mind', type:'PSYCHIC', category:'STATUS', power:0, accuracy:100, pp:10, priority:0, animStyle:'SELF',
    effect:{type:'STAT_RAISE',stats:['atk','spAtk'],stages:1}, description:'Mirrors the foe\'s power to boost both attacks.' },
  LEVITATE_STRIKE: { id:'LEVITATE_STRIKE', name:'Levitate Strike', type:'PSYCHIC', category:'PHYSICAL', power:75, accuracy:100, pp:15, priority:0, animStyle:'ARC',
    effect:{type:'NONE'}, description:'Levitates and strikes from an unpredictable angle.' },
  ORACLE_BEAM: { id:'ORACLE_BEAM', name:'Oracle Beam', type:'PSYCHIC', category:'SPECIAL', power:120, accuracy:80, pp:5, priority:0, animStyle:'BEAM',
    effect:{type:'STAT_LOWER',stat:'spAtk',stages:2}, description:'A prophetic beam of psychic power, draining focus.' },
  BRAIN_DRAIN: { id:'BRAIN_DRAIN', name:'Brain Drain', type:'PSYCHIC', category:'SPECIAL', power:70, accuracy:100, pp:15, priority:0, animStyle:'DRAIN',
    effect:{type:'DRAIN',fraction:50}, description:'Drains mental energy to heal the user.' },
  PSYCHIC_SHIELD: { id:'PSYCHIC_SHIELD', name:'Psychic Shield', type:'PSYCHIC', category:'STATUS', power:0, accuracy:100, pp:20, priority:0, animStyle:'SELF',
    effect:{type:'STAT_RAISE',stat:'spDef',stages:1}, description:'Creates a psychic shield that boosts Sp. Def.' },
  CHAOS_WAVE: { id:'CHAOS_WAVE', name:'Chaos Wave', type:'PSYCHIC', category:'SPECIAL', power:80, accuracy:90, pp:10, priority:0, animStyle:'WAVE',
    effect:{type:'CONFUSE',chance:30}, description:'A chaotic wave of psychic energy may confuse.' },
  FOCAL_BEAM: { id:'FOCAL_BEAM', name:'Focal Beam', type:'PSYCHIC', category:'SPECIAL', power:85, accuracy:100, pp:10, priority:0, animStyle:'BEAM',
    effect:{type:'NONE'}, description:'A laser-focused beam of pure psychic force.' },
  THIRD_EYE: { id:'THIRD_EYE', name:'Third Eye', type:'PSYCHIC', category:'STATUS', power:0, accuracy:100, pp:15, priority:0, animStyle:'AURA',
    effect:{type:'STAT_RAISE',stats:['spAtk','spDef'],stages:1}, description:'Opens the third eye, raising Sp. Atk and Sp. Def.' },

  // ═══════════════════════════════════════════════════════
  // PHASE 2 BATCH B — ROCK (25 new)
  // ═══════════════════════════════════════════════════════
  BOULDER_TOSS: { id:'BOULDER_TOSS', name:'Boulder Toss', type:'ROCK', category:'PHYSICAL', power:80, accuracy:90, pp:15, priority:0, animStyle:'PROJECTILE',
    effect:{type:'NONE'}, description:'Hurls a giant boulder at the foe.' },
  ROCK_STORM: { id:'ROCK_STORM', name:'Rock Storm', type:'ROCK', category:'PHYSICAL', power:65, accuracy:90, pp:15, priority:0, animStyle:'MULTI',
    effect:{type:'FLINCH',chance:20}, description:'A storm of rocks pelts the foe 2-5 times.' },
  STONE_EDGE_PLUS: { id:'STONE_EDGE_PLUS', name:'Crystal Edge', type:'ROCK', category:'PHYSICAL', power:100, accuracy:80, pp:8, priority:0, animStyle:'MELEE',
    effect:{type:'NONE'}, description:'A razor-edged crystal blade strikes with high crit rate.' },
  GRANITE_SHIELD: { id:'GRANITE_SHIELD', name:'Granite Shield', type:'ROCK', category:'STATUS', power:0, accuracy:100, pp:15, priority:0, animStyle:'SELF',
    effect:{type:'STAT_RAISE',stat:'def',stages:2}, description:'Encases the body in granite, sharply raising Defense.' },
  SHATTER: { id:'SHATTER', name:'Shatter', type:'ROCK', category:'PHYSICAL', power:75, accuracy:100, pp:15, priority:0, animStyle:'BURST',
    effect:{type:'STAT_LOWER',stat:'def',stages:1}, description:'Shatters rocks against the foe\'s armor.' },
  ROCK_AVALANCHE: { id:'ROCK_AVALANCHE', name:'Rock Avalanche', type:'ROCK', category:'PHYSICAL', power:90, accuracy:90, pp:10, priority:0, animStyle:'WAVE',
    effect:{type:'FLINCH',chance:30}, description:'An avalanche of rocks crashes down on the foe.' },
  FOSSIL_BEAM_ROCK: { id:'FOSSIL_BEAM_ROCK', name:'Fossil Beam', type:'ROCK', category:'SPECIAL', power:85, accuracy:100, pp:10, priority:0, animStyle:'BEAM',
    effect:{type:'NONE'}, description:'Fires a beam of condensed fossilized energy.' },
  STONE_SPEAR: { id:'STONE_SPEAR', name:'Stone Spear', type:'ROCK', category:'PHYSICAL', power:65, accuracy:100, pp:20, priority:0, animStyle:'PROJECTILE',
    effect:{type:'NONE'}, description:'A sharpened stone hurled like a javelin.' },
  PETRIFACTION: { id:'PETRIFACTION', name:'Petrifaction', type:'ROCK', category:'STATUS', power:0, accuracy:80, pp:10, priority:0, animStyle:'FIELD',
    effect:{type:'PARALYSIS',chance:100}, description:'Turns the foe\'s limbs to stone, paralyzing them.' },
  ANCIENT_POWER_PLUS: { id:'ANCIENT_POWER_PLUS', name:'Primal Force', type:'ROCK', category:'SPECIAL', power:80, accuracy:100, pp:10, priority:0, animStyle:'AURA',
    effect:{type:'OMNI_RAISE',chance:50}, description:'Ancient power has a 50% chance to raise all stats.' },
  ROCK_PULSE: { id:'ROCK_PULSE', name:'Rock Pulse', type:'ROCK', category:'SPECIAL', power:70, accuracy:100, pp:15, priority:0, animStyle:'PULSE',
    effect:{type:'NONE'}, description:'Pulses of seismic stone energy blast the foe.' },
  GEODE_SLAM: { id:'GEODE_SLAM', name:'Geode Slam', type:'ROCK', category:'PHYSICAL', power:100, accuracy:90, pp:10, priority:0, animStyle:'SLAM',
    effect:{type:'FLINCH',chance:20}, description:'Smashes with a massive crystalline geode.' },
  MINERAL_BURST: { id:'MINERAL_BURST', name:'Mineral Burst', type:'ROCK', category:'PHYSICAL', power:50, accuracy:100, pp:25, priority:0, animStyle:'MULTI',
    effect:{type:'MULTI_HIT',hits:'2-5'}, description:'Launches shards of mineral at high speed.' },
  EARTH_BUSTER: { id:'EARTH_BUSTER', name:'Earth Buster', type:'ROCK', category:'PHYSICAL', power:110, accuracy:90, pp:8, priority:0, animStyle:'SLAM',
    effect:{type:'NONE'}, description:'Buries the foe under a titanic stone fist.' },
  CRYSTAL_LANCE: { id:'CRYSTAL_LANCE', name:'Crystal Lance', type:'ROCK', category:'PHYSICAL', power:80, accuracy:100, pp:10, priority:0, animStyle:'MELEE',
    effect:{type:'FREEZE_CHANCE',chance:10}, description:'A lance of pure crystal may freeze on contact.' },
  GRAVEL_STORM: { id:'GRAVEL_STORM', name:'Gravel Storm', type:'ROCK', category:'SPECIAL', power:55, accuracy:90, pp:20, priority:0, animStyle:'VORTEX',
    effect:{type:'STAT_LOWER',stat:'acc',stages:1}, description:'A storm of gravel lowers accuracy.' },
  ROCK_CANNON: { id:'ROCK_CANNON', name:'Rock Cannon', type:'ROCK', category:'PHYSICAL', power:95, accuracy:85, pp:10, priority:0, animStyle:'PROJECTILE',
    effect:{type:'NONE'}, description:'Fires a cannonball-sized stone at the foe.' },
  STONE_SURGE: { id:'STONE_SURGE', name:'Stone Surge', type:'ROCK', category:'SPECIAL', power:70, accuracy:100, pp:15, priority:0, animStyle:'BURST',
    effect:{type:'NONE'}, description:'A surge of stone fragments erupts upward.' },
  BEDROCK_PULSE: { id:'BEDROCK_PULSE', name:'Bedrock Pulse', type:'ROCK', category:'SPECIAL', power:80, accuracy:100, pp:10, priority:0, animStyle:'PULSE',
    effect:{type:'NONE'}, description:'Pulses from deep bedrock resonate through the foe.' },
  AMBER_TRAP: { id:'AMBER_TRAP', name:'Amber Trap', type:'ROCK', category:'STATUS', power:0, accuracy:90, pp:15, priority:0, animStyle:'FIELD',
    effect:{type:'PARALYSIS',chance:100}, description:'Encases the foe in ancient amber.' },
  MOUNTAIN_CRASH: { id:'MOUNTAIN_CRASH', name:'Mountain Crash', type:'ROCK', category:'PHYSICAL', power:120, accuracy:85, pp:8, priority:0, animStyle:'SLAM',
    effect:{type:'RECOIL',fraction:25}, description:'The force of a mountain brought down on the foe.' },
  ROCK_VEIL: { id:'ROCK_VEIL', name:'Rock Veil', type:'ROCK', category:'STATUS', power:0, accuracy:100, pp:15, priority:0, animStyle:'SELF',
    effect:{type:'STAT_RAISE',stats:['def','spDef'],stages:1}, description:'A veil of rock fragments boosts both defenses.' },
  SPLINTER: { id:'SPLINTER', name:'Splinter', type:'ROCK', category:'PHYSICAL', power:60, accuracy:100, pp:20, priority:0, animStyle:'MULTI',
    effect:{type:'NONE'}, description:'Sharp rock splinters slice the foe 2-5 times.' },
  TECTONIC_PULSE: { id:'TECTONIC_PULSE', name:'Tectonic Pulse', type:'ROCK', category:'SPECIAL', power:90, accuracy:90, pp:10, priority:0, animStyle:'PULSE',
    effect:{type:'NONE'}, description:'Tectonic energy pulses from beneath the battlefield.' },
  STONE_WALL: { id:'STONE_WALL', name:'Stone Wall', type:'ROCK', category:'STATUS', power:0, accuracy:100, pp:20, priority:0, animStyle:'SELF',
    effect:{type:'STAT_RAISE',stat:'def',stages:1}, description:'Raises a stone wall to boost Defense.' },

  // ═══════════════════════════════════════════════════════
  // PHASE 2 BATCH B — GHOST (20 new)
  // ═══════════════════════════════════════════════════════
  SPIRIT_BURST: { id:'SPIRIT_BURST', name:'Spirit Burst', type:'GHOST', category:'SPECIAL', power:85, accuracy:100, pp:10, priority:0, animStyle:'BURST',
    effect:{type:'NONE'}, description:'The trapped energy of spirits bursts outward.' },
  WRAITH_SLASH: { id:'WRAITH_SLASH', name:'Wraith Slash', type:'GHOST', category:'PHYSICAL', power:70, accuracy:100, pp:15, priority:0, animStyle:'MELEE',
    effect:{type:'FLINCH',chance:20}, description:'A spectral slash from a passing wraith.' },
  HAUNTING_PULSE: { id:'HAUNTING_PULSE', name:'Haunting Pulse', type:'GHOST', category:'SPECIAL', power:75, accuracy:100, pp:15, priority:0, animStyle:'PULSE',
    effect:{type:'CONFUSE',chance:30}, description:'Haunting vibrations may confuse the foe.' },
  GHOST_WAVE: { id:'GHOST_WAVE', name:'Ghost Wave', type:'GHOST', category:'SPECIAL', power:65, accuracy:100, pp:20, priority:0, animStyle:'WAVE',
    effect:{type:'NONE'}, description:'A wave of ghostly energy washes over the foe.' },
  SHADOW_BURST: { id:'SHADOW_BURST', name:'Shadow Burst', type:'GHOST', category:'SPECIAL', power:90, accuracy:95, pp:10, priority:0, animStyle:'BURST',
    effect:{type:'STAT_LOWER',stat:'def',stages:1}, description:'A burst of shadows lowers Defense.' },
  SOUL_SPIKE: { id:'SOUL_SPIKE', name:'Soul Spike', type:'GHOST', category:'SPECIAL', power:60, accuracy:100, pp:20, priority:0, animStyle:'PROJECTILE',
    effect:{type:'NONE'}, description:'A spike of pure soul energy pierces the foe.' },
  PHANTOM_PULSE: { id:'PHANTOM_PULSE', name:'Phantom Pulse', type:'GHOST', category:'SPECIAL', power:80, accuracy:100, pp:10, priority:0, animStyle:'PULSE',
    effect:{type:'CONFUSE',chance:20}, description:'Phantom vibrations may cause confusion.' },
  SPECTER_BEAM: { id:'SPECTER_BEAM', name:'Specter Beam', type:'GHOST', category:'SPECIAL', power:100, accuracy:90, pp:10, priority:0, animStyle:'BEAM',
    effect:{type:'NONE'}, description:'A beam of spectral energy from the beyond.' },
  DARK_VOID: { id:'DARK_VOID', name:'Dark Void', type:'GHOST', category:'STATUS', power:0, accuracy:80, pp:10, priority:0, animStyle:'VORTEX',
    effect:{type:'SLEEP',chance:100}, description:'Pulls the foe into a dimension of endless sleep.' },
  GRUDGE_STRIKE: { id:'GRUDGE_STRIKE', name:'Grudge Strike', type:'GHOST', category:'PHYSICAL', power:95, accuracy:90, pp:10, priority:0, animStyle:'MELEE',
    effect:{type:'NONE'}, description:'Strikes with the force of lingering grudges.' },
  TERROR_WAVE: { id:'TERROR_WAVE', name:'Terror Wave', type:'GHOST', category:'STATUS', power:0, accuracy:100, pp:15, priority:0, animStyle:'FIELD',
    effect:{type:'STAT_LOWER',stat:'atk',stages:2}, description:'Terrifying aura sharply lowers the foe\'s Attack.' },
  BANISH: { id:'BANISH', name:'Banish', type:'GHOST', category:'SPECIAL', power:80, accuracy:95, pp:10, priority:0, animStyle:'VORTEX',
    effect:{type:'NONE'}, description:'Banishes the foe to another dimension temporarily.' },
  CURSED_TOUCH: { id:'CURSED_TOUCH', name:'Cursed Touch', type:'GHOST', category:'PHYSICAL', power:65, accuracy:100, pp:15, priority:0, animStyle:'MELEE',
    effect:{type:'POISON_CHANCE',chance:30}, description:'A cursed hand poisons on contact.' },
  AFTERLIFE_BLAST: { id:'AFTERLIFE_BLAST', name:'Afterlife Blast', type:'GHOST', category:'SPECIAL', power:110, accuracy:85, pp:8, priority:0, animStyle:'BURST',
    effect:{type:'NONE'}, description:'A blast of energy from the great beyond.' },
  ECTOPLASM: { id:'ECTOPLASM', name:'Ectoplasm', type:'GHOST', category:'SPECIAL', power:70, accuracy:100, pp:15, priority:0, animStyle:'PROJECTILE',
    effect:{type:'STAT_LOWER',stat:'spDef',stages:1}, description:'Gooey ectoplasm lowers Sp. Def.' },
  GRAVE_WIND: { id:'GRAVE_WIND', name:'Grave Wind', type:'GHOST', category:'STATUS', power:0, accuracy:100, pp:15, priority:0, animStyle:'SELF',
    effect:{type:'STAT_RAISE',stat:'spAtk',stages:2}, description:'Wind from the grave sharply raises Sp. Atk.' },
  PHANTOM_FORCE_BLAST: { id:'PHANTOM_FORCE_BLAST', name:'Ghost Charge', type:'GHOST', category:'PHYSICAL', power:90, accuracy:100, pp:10, priority:0, animStyle:'SLAM',
    effect:{type:'TWO_TURN'}, description:'Vanishes then strikes from another plane.' },
  SHADOWSTEP: { id:'SHADOWSTEP', name:'Shadowstep', type:'GHOST', category:'PHYSICAL', power:60, accuracy:100, pp:20, priority:1, animStyle:'ARC',
    effect:{type:'NONE'}, description:'Steps through shadows to strike with priority.' },
  SPECTER_DRAIN: { id:'SPECTER_DRAIN', name:'Specter Drain', type:'GHOST', category:'SPECIAL', power:75, accuracy:100, pp:10, priority:0, animStyle:'DRAIN',
    effect:{type:'DRAIN',fraction:50}, description:'Drains life force through spectral contact.' },
  BONE_RUSH_GHOST: { id:'BONE_RUSH_GHOST', name:'Ghost Bone', type:'GHOST', category:'PHYSICAL', power:50, accuracy:90, pp:20, priority:0, animStyle:'MULTI',
    effect:{type:'MULTI_HIT',hits:'2-5'}, description:'Slaps with ghostly bones 2-5 times.' },

  // ═══════════════════════════════════════════════════════
  // PHASE 2 BATCH B — DRAGON (20 new)
  // ═══════════════════════════════════════════════════════
  PRIMAL_DRAGON: { id:'PRIMAL_DRAGON', name:'Primal Dragon', type:'DRAGON', category:'SPECIAL', power:110, accuracy:90, pp:8, priority:0, animStyle:'BURST',
    effect:{type:'NONE'}, description:'Channels primordial dragon energy for a massive blast.' },
  SCALE_STORM: { id:'SCALE_STORM', name:'Scale Storm', type:'DRAGON', category:'PHYSICAL', power:70, accuracy:90, pp:15, priority:0, animStyle:'MULTI',
    effect:{type:'STAT_RAISE',stat:'spd',stages:1}, description:'Fires scales rapidly, raising the user\'s Speed.' },
  DRAGON_RUSH_CLAW: { id:'DRAGON_RUSH_CLAW', name:'Dragon Claw Rush', type:'DRAGON', category:'PHYSICAL', power:80, accuracy:100, pp:15, priority:0, animStyle:'MELEE',
    effect:{type:'NONE'}, description:'Rushing claws infused with draconic power.' },
  ANCIENT_WRATH: { id:'ANCIENT_WRATH', name:'Ancient Wrath', type:'DRAGON', category:'SPECIAL', power:100, accuracy:90, pp:10, priority:0, animStyle:'BURST',
    effect:{type:'NONE'}, description:'The wrath of ancient dragons unleashed.' },
  FOSSIL_DRAGON: { id:'FOSSIL_DRAGON', name:'Fossil Dragon', type:'DRAGON', category:'SPECIAL', power:90, accuracy:100, pp:10, priority:0, animStyle:'BEAM',
    effect:{type:'NONE'}, description:'Fossilized dragon energy condensed into a beam.' },
  WING_BLAST: { id:'WING_BLAST', name:'Wing Blast', type:'DRAGON', category:'PHYSICAL', power:75, accuracy:100, pp:15, priority:0, animStyle:'ARC',
    effect:{type:'NONE'}, description:'A powerful flap sends a dragon-wind blast.' },
  DRACO_WAVE: { id:'DRACO_WAVE', name:'Draco Wave', type:'DRAGON', category:'SPECIAL', power:80, accuracy:100, pp:10, priority:0, animStyle:'WAVE',
    effect:{type:'NONE'}, description:'A wave of draconic energy rolls across the field.' },
  DRAGON_DIVE: { id:'DRAGON_DIVE', name:'Dragon Dive', type:'DRAGON', category:'PHYSICAL', power:100, accuracy:90, pp:10, priority:0, animStyle:'SLAM',
    effect:{type:'FLINCH',chance:20}, description:'Dives from altitude cloaked in dragon energy.' },
  DRAGON_STORM: { id:'DRAGON_STORM', name:'Dragon Storm', type:'DRAGON', category:'SPECIAL', power:95, accuracy:85, pp:10, priority:0, animStyle:'VORTEX',
    effect:{type:'NONE'}, description:'A storm brewed from draconic power.' },
  SERPENT_STRIKE: { id:'SERPENT_STRIKE', name:'Serpent Strike', type:'DRAGON', category:'PHYSICAL', power:65, accuracy:100, pp:20, priority:0, animStyle:'MELEE',
    effect:{type:'POISON_CHANCE',chance:20}, description:'A dragon-serpent bite may poison the foe.' },
  APEX_DRAGON: { id:'APEX_DRAGON', name:'Apex Dragon', type:'DRAGON', category:'PHYSICAL', power:120, accuracy:85, pp:5, priority:0, animStyle:'BURST',
    effect:{type:'RECOIL',fraction:25}, description:'The apex predator strike of dragonkind.' },
  DRAGON_PULSE_SURGE: { id:'DRAGON_PULSE_SURGE', name:'Dragon Surge', type:'DRAGON', category:'SPECIAL', power:85, accuracy:100, pp:10, priority:0, animStyle:'PULSE',
    effect:{type:'NONE'}, description:'A surging pulse of dragon-fire energy.' },
  PRIMORDIAL_BREATH: { id:'PRIMORDIAL_BREATH', name:'Primordial Breath', type:'DRAGON', category:'SPECIAL', power:90, accuracy:90, pp:10, priority:0, animStyle:'CONE',
    effect:{type:'BURN_CHANCE',chance:20}, description:'The first flame breathed by the oldest dragons.' },
  DRAGON_FANG: { id:'DRAGON_FANG', name:'Dragon Fang', type:'DRAGON', category:'PHYSICAL', power:60, accuracy:100, pp:20, priority:0, animStyle:'MELEE',
    effect:{type:'FLINCH',chance:20}, description:'A fearsome dragon bite may cause flinching.' },
  WYVERN_STRIKE: { id:'WYVERN_STRIKE', name:'Wyvern Strike', type:'DRAGON', category:'PHYSICAL', power:85, accuracy:95, pp:10, priority:0, animStyle:'ARC',
    effect:{type:'NONE'}, description:'A wyvern\'s signature aerial slash.' },
  SCALE_SHOT_PLUS: { id:'SCALE_SHOT_PLUS', name:'Scale Barrage', type:'DRAGON', category:'PHYSICAL', power:50, accuracy:90, pp:20, priority:0, animStyle:'MULTI',
    effect:{type:'MULTI_HIT',hits:'2-5'}, description:'Fires scales like arrows 2-5 times.' },
  DRAGON_ASCENT: { id:'DRAGON_ASCENT', name:'Dragon Ascent', type:'DRAGON', category:'PHYSICAL', power:110, accuracy:90, pp:10, priority:0, animStyle:'ARC',
    effect:{type:'STAT_LOWER',stats:['def','spDef'],stages:1}, description:'Soars then crashes, lowering user\'s defenses.' },
  CLAW_STORM: { id:'CLAW_STORM', name:'Claw Storm', type:'DRAGON', category:'PHYSICAL', power:50, accuracy:100, pp:20, priority:0, animStyle:'MULTI',
    effect:{type:'MULTI_HIT',hits:'2-5'}, description:'Dragon claws shred the foe 2-5 times.' },
  DRACONIC_AURA: { id:'DRACONIC_AURA', name:'Draconic Aura', type:'DRAGON', category:'STATUS', power:0, accuracy:100, pp:10, priority:0, animStyle:'AURA',
    effect:{type:'STAT_RAISE',stats:['atk','spAtk'],stages:1}, description:'Radiates draconic aura, boosting both attacks.' },
  PREHISTORY: { id:'PREHISTORY', name:'Prehistory', type:'DRAGON', category:'SPECIAL', power:130, accuracy:90, pp:5, priority:0, animStyle:'BURST',
    effect:{type:'RECHARGE'}, description:'Invokes the power of prehistoric dragons. Must recharge.' },

  // ═══════════════════════════════════════════════════════
  // PHASE 2 BATCH B — DARK (20 new)
  // ═══════════════════════════════════════════════════════
  SHADOW_STORM: { id:'SHADOW_STORM', name:'Shadow Storm', type:'DARK', category:'SPECIAL', power:90, accuracy:90, pp:10, priority:0, animStyle:'VORTEX',
    effect:{type:'STAT_LOWER',stat:'spDef',stages:1}, description:'A storm of shadows lowers Sp. Def.' },
  NIGHT_SLASH_SURGE: { id:'NIGHT_SLASH_SURGE', name:'Night Rush', type:'DARK', category:'PHYSICAL', power:75, accuracy:100, pp:15, priority:0, animStyle:'MELEE',
    effect:{type:'NONE'}, description:'A swift strike in total darkness with high crit rate.' },
  DARK_PULSE_WAVE: { id:'DARK_PULSE_WAVE', name:'Dark Surge', type:'DARK', category:'SPECIAL', power:80, accuracy:100, pp:10, priority:0, animStyle:'WAVE',
    effect:{type:'CONFUSE',chance:20}, description:'A dark wave may confuse the foe.' },
  VOID_BLAST: { id:'VOID_BLAST', name:'Void Blast', type:'DARK', category:'SPECIAL', power:100, accuracy:90, pp:10, priority:0, animStyle:'BURST',
    effect:{type:'NONE'}, description:'A blast from the void of absolute darkness.' },
  SHADOW_BITE: { id:'SHADOW_BITE', name:'Shadow Bite', type:'DARK', category:'PHYSICAL', power:65, accuracy:100, pp:15, priority:0, animStyle:'MELEE',
    effect:{type:'FLINCH',chance:30}, description:'A bite from the shadows may cause flinching.' },
  DARK_VEIL: { id:'DARK_VEIL', name:'Dark Veil', type:'DARK', category:'STATUS', power:0, accuracy:100, pp:20, priority:0, animStyle:'SELF',
    effect:{type:'STAT_RAISE',stat:'atk',stages:1}, description:'Shrouds the user in darkness, raising Attack.' },
  ECLIPSE_BEAM: { id:'ECLIPSE_BEAM', name:'Eclipse Beam', type:'DARK', category:'SPECIAL', power:95, accuracy:95, pp:10, priority:0, animStyle:'BEAM',
    effect:{type:'NONE'}, description:'A beam of eclipsed sunlight, pure darkness.' },
  OBLIVION_PULSE: { id:'OBLIVION_PULSE', name:'Oblivion Pulse', type:'DARK', category:'SPECIAL', power:80, accuracy:100, pp:10, priority:0, animStyle:'PULSE',
    effect:{type:'STAT_LOWER',stat:'spDef',stages:1}, description:'Pulses of oblivion energy erode Sp. Def.' },
  MIDNIGHT_CLAW: { id:'MIDNIGHT_CLAW', name:'Midnight Claw', type:'DARK', category:'PHYSICAL', power:80, accuracy:100, pp:10, priority:0, animStyle:'MELEE',
    effect:{type:'NONE'}, description:'Strikes from the darkness of midnight.' },
  DUSK_SLAM: { id:'DUSK_SLAM', name:'Dusk Slam', type:'DARK', category:'PHYSICAL', power:90, accuracy:95, pp:10, priority:0, animStyle:'SLAM',
    effect:{type:'NONE'}, description:'A devastating slam wrapped in dusk shadow.' },
  TERROR_BITE: { id:'TERROR_BITE', name:'Terror Bite', type:'DARK', category:'PHYSICAL', power:85, accuracy:90, pp:10, priority:0, animStyle:'MELEE',
    effect:{type:'STAT_LOWER',stat:'def',stages:1}, description:'A terrifying bite can crack any defense.' },
  ABYSS_WAVE: { id:'ABYSS_WAVE', name:'Abyss Wave', type:'DARK', category:'SPECIAL', power:85, accuracy:100, pp:10, priority:0, animStyle:'WAVE',
    effect:{type:'NONE'}, description:'A wave from the abyss swallows the foe.' },
  SHADOW_AURA: { id:'SHADOW_AURA', name:'Shadow Aura', type:'DARK', category:'STATUS', power:0, accuracy:100, pp:10, priority:0, animStyle:'AURA',
    effect:{type:'STAT_RAISE',stats:['atk','def'],stages:1}, description:'Shadow aura hardens the body, raising Atk and Def.' },
  DARK_VORTEX: { id:'DARK_VORTEX', name:'Dark Vortex', type:'DARK', category:'SPECIAL', power:75, accuracy:100, pp:15, priority:0, animStyle:'VORTEX',
    effect:{type:'CONFUSE',chance:30}, description:'Pulls the foe into a dark spiral of confusion.' },
  NIGHT_TERROR: { id:'NIGHT_TERROR', name:'Night Terror', type:'DARK', category:'SPECIAL', power:70, accuracy:100, pp:15, priority:0, animStyle:'BURST',
    effect:{type:'FLINCH',chance:20}, description:'Terrifying dark energy may cause flinching.' },
  DARKNESS_STRIKE: { id:'DARKNESS_STRIKE', name:'Darkness Strike', type:'DARK', category:'PHYSICAL', power:95, accuracy:90, pp:10, priority:0, animStyle:'MELEE',
    effect:{type:'NONE'}, description:'A strike cloaked in impenetrable darkness.' },
  DARK_DRAIN: { id:'DARK_DRAIN', name:'Dark Drain', type:'DARK', category:'SPECIAL', power:65, accuracy:100, pp:15, priority:0, animStyle:'DRAIN',
    effect:{type:'DRAIN',fraction:50}, description:'Drains energy through dark absorption.' },
  SHADOW_CANNON: { id:'SHADOW_CANNON', name:'Shadow Cannon', type:'DARK', category:'SPECIAL', power:110, accuracy:85, pp:8, priority:0, animStyle:'BEAM',
    effect:{type:'NONE'}, description:'Fires a cannon blast of condensed shadow.' },
  CORRUPT: { id:'CORRUPT', name:'Corrupt', type:'DARK', category:'STATUS', power:0, accuracy:90, pp:15, priority:0, animStyle:'FIELD',
    effect:{type:'STAT_LOWER',stats:['atk','spAtk'],stages:1}, description:'Corrupts the foe\'s power, lowering both attacks.' },
  NIGHT_DIVE: { id:'NIGHT_DIVE', name:'Night Dive', type:'DARK', category:'PHYSICAL', power:100, accuracy:90, pp:10, priority:0, animStyle:'ARC',
    effect:{type:'TWO_TURN'}, description:'Vanishes into darkness then dives on the foe.' },

  // ═══════════════════════════════════════════════════════
  // PHASE 2 BATCH B — STEEL (20 new)
  // ═══════════════════════════════════════════════════════
  IRON_STORM: { id:'IRON_STORM', name:'Iron Storm', type:'STEEL', category:'PHYSICAL', power:70, accuracy:90, pp:15, priority:0, animStyle:'MULTI',
    effect:{type:'NONE'}, description:'A storm of iron shards strikes 2-5 times.' },
  TITANIUM_STRIKE: { id:'TITANIUM_STRIKE', name:'Titanium Strike', type:'STEEL', category:'PHYSICAL', power:90, accuracy:100, pp:10, priority:0, animStyle:'MELEE',
    effect:{type:'NONE'}, description:'A strike with titanium-hardened limbs.' },
  STEEL_SURGE: { id:'STEEL_SURGE', name:'Steel Surge', type:'STEEL', category:'PHYSICAL', power:80, accuracy:100, pp:10, priority:0, animStyle:'WAVE',
    effect:{type:'NONE'}, description:'A surge of steel shards sweeps the battlefield.' },
  MAGNETISM: { id:'MAGNETISM', name:'Magnetism', type:'STEEL', category:'STATUS', power:0, accuracy:100, pp:20, priority:0, animStyle:'FIELD',
    effect:{type:'PARALYSIS',chance:100}, description:'Magnetizes the foe\'s metallic parts, paralyzing them.' },
  IRON_WAVE: { id:'IRON_WAVE', name:'Iron Wave', type:'STEEL', category:'PHYSICAL', power:75, accuracy:100, pp:15, priority:0, animStyle:'WAVE',
    effect:{type:'NONE'}, description:'A wave of iron energy crashes into the foe.' },
  STEEL_DRILL: { id:'STEEL_DRILL', name:'Steel Drill', type:'STEEL', category:'PHYSICAL', power:85, accuracy:95, pp:10, priority:0, animStyle:'MELEE',
    effect:{type:'STAT_LOWER',stat:'def',stages:1}, description:'Drills through defenses, lowering Defense.' },
  ALLOY_SHIELD: { id:'ALLOY_SHIELD', name:'Alloy Shield', type:'STEEL', category:'STATUS', power:0, accuracy:100, pp:15, priority:0, animStyle:'SELF',
    effect:{type:'STAT_RAISE',stats:['def','spDef'],stages:1}, description:'A multi-alloy shield boosts both defenses.' },
  CHROME_BLAST: { id:'CHROME_BLAST', name:'Chrome Blast', type:'STEEL', category:'SPECIAL', power:80, accuracy:100, pp:10, priority:0, animStyle:'BURST',
    effect:{type:'NONE'}, description:'Polished chrome redirects energy into a blast.' },
  STEEL_VORTEX: { id:'STEEL_VORTEX', name:'Steel Vortex', type:'STEEL', category:'PHYSICAL', power:90, accuracy:90, pp:10, priority:0, animStyle:'VORTEX',
    effect:{type:'NONE'}, description:'A vortex of steel shards engulfs the foe.' },
  FORGE_SLAM: { id:'FORGE_SLAM', name:'Forge Slam', type:'STEEL', category:'PHYSICAL', power:100, accuracy:90, pp:10, priority:0, animStyle:'SLAM',
    effect:{type:'NONE'}, description:'Slams with a limb heated in the forge.' },
  ALLOY_STRIKE: { id:'ALLOY_STRIKE', name:'Alloy Strike', type:'STEEL', category:'PHYSICAL', power:70, accuracy:100, pp:15, priority:0, animStyle:'MELEE',
    effect:{type:'NONE'}, description:'Strikes with a body reinforced with rare alloys.' },
  MAGNETIZE: { id:'MAGNETIZE', name:'Magnetize', type:'STEEL', category:'STATUS', power:0, accuracy:100, pp:15, priority:0, animStyle:'SELF',
    effect:{type:'STAT_RAISE',stat:'atk',stages:2}, description:'Magnetizes the body, sharply raising Attack.' },
  STEEL_BEAM_PLUS: { id:'STEEL_BEAM_PLUS', name:'Ferrous Beam', type:'STEEL', category:'SPECIAL', power:140, accuracy:95, pp:5, priority:0, animStyle:'BEAM',
    effect:{type:'RECOIL',fraction:50}, description:'Fires a beam of ferrous energy from the body core.' },
  IRON_CAGE: { id:'IRON_CAGE', name:'Iron Cage', type:'STEEL', category:'STATUS', power:0, accuracy:90, pp:15, priority:0, animStyle:'FIELD',
    effect:{type:'PARALYSIS',chance:100}, description:'An iron cage traps the foe, preventing escape.' },
  BLADE_STORM: { id:'BLADE_STORM', name:'Blade Storm', type:'STEEL', category:'PHYSICAL', power:60, accuracy:95, pp:20, priority:0, animStyle:'MULTI',
    effect:{type:'MULTI_HIT',hits:'2-5'}, description:'Steel blades slice the foe 2-5 times.' },
  TUNGSTEN_CRASH: { id:'TUNGSTEN_CRASH', name:'Tungsten Crash', type:'STEEL', category:'PHYSICAL', power:110, accuracy:90, pp:8, priority:0, animStyle:'SLAM',
    effect:{type:'NONE'}, description:'Crashes with the density of pure tungsten.' },
  STEEL_PULSE: { id:'STEEL_PULSE', name:'Steel Pulse', type:'STEEL', category:'SPECIAL', power:65, accuracy:100, pp:15, priority:0, animStyle:'PULSE',
    effect:{type:'NONE'}, description:'Metal resonates in a pulse of steel energy.' },
  ARMOR_CRUSH: { id:'ARMOR_CRUSH', name:'Armor Crush', type:'STEEL', category:'PHYSICAL', power:80, accuracy:95, pp:10, priority:0, animStyle:'MELEE',
    effect:{type:'STAT_LOWER',stat:'def',stages:2}, description:'Crushes through armor, sharply lowering Defense.' },
  METAL_BURST_STEEL: { id:'METAL_BURST_STEEL', name:'Metal Burst', type:'STEEL', category:'SPECIAL', power:0, accuracy:100, pp:10, priority:0, animStyle:'BURST',
    effect:{type:'NONE'}, description:'Returns damage dealt in the same turn with greater force.' },
  STEEL_AURA: { id:'STEEL_AURA', name:'Steel Aura', type:'STEEL', category:'STATUS', power:0, accuracy:100, pp:10, priority:0, animStyle:'AURA',
    effect:{type:'STAT_RAISE',stat:'def',stages:3}, description:'Radiates steel aura, drastically raising Defense.' },

  // ═══════════════════════════════════════════════════════
  // PHASE 2 BATCH B — FAIRY (20 new)
  // ═══════════════════════════════════════════════════════
  FAIRY_BURST: { id:'FAIRY_BURST', name:'Fairy Burst', type:'FAIRY', category:'SPECIAL', power:85, accuracy:100, pp:10, priority:0, animStyle:'BURST',
    effect:{type:'NONE'}, description:'A burst of sparkling fairy energy.' },
  STARDUST_BEAM: { id:'STARDUST_BEAM', name:'Stardust Beam', type:'FAIRY', category:'SPECIAL', power:80, accuracy:100, pp:10, priority:0, animStyle:'BEAM',
    effect:{type:'NONE'}, description:'A beam of stardust light blinds and damages.' },
  FAIRY_VORTEX: { id:'FAIRY_VORTEX', name:'Fairy Vortex', type:'FAIRY', category:'SPECIAL', power:75, accuracy:100, pp:15, priority:0, animStyle:'VORTEX',
    effect:{type:'CONFUSE',chance:30}, description:'A swirling fairy vortex may confuse the foe.' },
  MOONBEAM: { id:'MOONBEAM', name:'Moonbeam', type:'FAIRY', category:'SPECIAL', power:90, accuracy:100, pp:10, priority:0, animStyle:'BEAM',
    effect:{type:'NONE'}, description:'Pure moonlight condensed into a damaging beam.' },
  ENCHANT: { id:'ENCHANT', name:'Enchant', type:'FAIRY', category:'STATUS', power:0, accuracy:100, pp:15, priority:0, animStyle:'AURA',
    effect:{type:'STAT_RAISE',stat:'spAtk',stages:2}, description:'Enchants the user, sharply raising Sp. Atk.' },
  PETAL_WAVE: { id:'PETAL_WAVE', name:'Petal Wave', type:'FAIRY', category:'SPECIAL', power:70, accuracy:100, pp:15, priority:0, animStyle:'WAVE',
    effect:{type:'NONE'}, description:'A wave of enchanted petals washes over the foe.' },
  FAIRY_SLAM: { id:'FAIRY_SLAM', name:'Fairy Slam', type:'FAIRY', category:'PHYSICAL', power:80, accuracy:100, pp:10, priority:0, animStyle:'SLAM',
    effect:{type:'NONE'}, description:'Slams with a fist crackling with fairy energy.' },
  GLITTER_BEAM: { id:'GLITTER_BEAM', name:'Glitter Beam', type:'FAIRY', category:'SPECIAL', power:65, accuracy:100, pp:20, priority:0, animStyle:'BEAM',
    effect:{type:'STAT_LOWER',stat:'spDef',stages:1}, description:'Glittering beam lowers the foe\'s Sp. Def.' },
  SPARKLE_STORM: { id:'SPARKLE_STORM', name:'Sparkle Storm', type:'FAIRY', category:'SPECIAL', power:75, accuracy:95, pp:15, priority:0, animStyle:'MULTI',
    effect:{type:'NONE'}, description:'A storm of sparkling light strikes 2-5 times.' },
  FAIRY_DRAIN: { id:'FAIRY_DRAIN', name:'Fairy Drain', type:'FAIRY', category:'SPECIAL', power:65, accuracy:100, pp:15, priority:0, animStyle:'DRAIN',
    effect:{type:'DRAIN',fraction:50}, description:'Draws vital energy through fairy magic.' },
  WISH_WAVE: { id:'WISH_WAVE', name:'Wish Wave', type:'FAIRY', category:'STATUS', power:0, accuracy:100, pp:10, priority:0, animStyle:'SELF',
    effect:{type:'HEAL',fraction:50}, description:'Makes a wish to restore half the user\'s HP.' },
  STARDUST_STORM: { id:'STARDUST_STORM', name:'Stardust Storm', type:'FAIRY', category:'SPECIAL', power:90, accuracy:90, pp:10, priority:0, animStyle:'VORTEX',
    effect:{type:'NONE'}, description:'A dazzling storm of cosmic stardust.' },
  FAIRY_PULSE: { id:'FAIRY_PULSE', name:'Fairy Pulse', type:'FAIRY', category:'SPECIAL', power:70, accuracy:100, pp:15, priority:0, animStyle:'PULSE',
    effect:{type:'CONFUSE',chance:20}, description:'Pulsing fairy energy may confuse the foe.' },
  GLISTENING_STRIKE: { id:'GLISTENING_STRIKE', name:'Glistening Strike', type:'FAIRY', category:'PHYSICAL', power:75, accuracy:100, pp:15, priority:0, animStyle:'MELEE',
    effect:{type:'NONE'}, description:'A strike shining with brilliant fairy light.' },
  AURORA_VEIL_ATK: { id:'AURORA_VEIL_ATK', name:'Aurora Strike', type:'FAIRY', category:'SPECIAL', power:80, accuracy:100, pp:10, priority:0, animStyle:'ARC',
    effect:{type:'NONE'}, description:'Strikes with an aurora of fairy energy.' },
  PIXIE_DUST: { id:'PIXIE_DUST', name:'Pixie Dust', type:'FAIRY', category:'STATUS', power:0, accuracy:100, pp:20, priority:0, animStyle:'FIELD',
    effect:{type:'STAT_LOWER',stat:'acc',stages:1}, description:'Scatters pixie dust that clouds vision.' },
  FAIRY_AURA: { id:'FAIRY_AURA', name:'Fairy Aura', type:'FAIRY', category:'STATUS', power:0, accuracy:100, pp:10, priority:0, animStyle:'AURA',
    effect:{type:'STAT_RAISE',stats:['spAtk','spDef'],stages:1}, description:'Fairy aura raises Sp. Atk and Sp. Def.' },
  TWINKLE_BEAM: { id:'TWINKLE_BEAM', name:'Twinkle Beam', type:'FAIRY', category:'SPECIAL', power:55, accuracy:100, pp:25, priority:0, animStyle:'BEAM',
    effect:{type:'CONFUSE',chance:10}, description:'A twinkling beam of starlight may confuse.' },
  LUNAR_BLAST: { id:'LUNAR_BLAST', name:'Lunar Blast', type:'FAIRY', category:'SPECIAL', power:110, accuracy:90, pp:8, priority:0, animStyle:'BURST',
    effect:{type:'NONE'}, description:'Full moon energy condensed into a devastating blast.' },
  RAINBOW_BEAM: { id:'RAINBOW_BEAM', name:'Rainbow Beam', type:'FAIRY', category:'SPECIAL', power:85, accuracy:100, pp:10, priority:0, animStyle:'BEAM',
    effect:{type:'NONE'}, description:'A beam refracting through every color of light.' },

  // ═══════════════════════════════════════════════════════
  // PHASE 2 BATCH B — BUG (20 new)
  // ═══════════════════════════════════════════════════════
  BUG_STORM: { id:'BUG_STORM', name:'Bug Storm', type:'BUG', category:'SPECIAL', power:90, accuracy:90, pp:10, priority:0, animStyle:'VORTEX',
    effect:{type:'NONE'}, description:'A swarm of bugs descends in a violent storm.' },
  SWARM_STRIKE_PLUS: { id:'SWARM_STRIKE_PLUS', name:'Swarm Crash', type:'BUG', category:'PHYSICAL', power:80, accuracy:100, pp:10, priority:0, animStyle:'SLAM',
    effect:{type:'NONE'}, description:'Crashes into the foe with the force of a whole swarm.' },
  SILK_THREAD: { id:'SILK_THREAD', name:'Silk Thread', type:'BUG', category:'STATUS', power:0, accuracy:100, pp:20, priority:0, animStyle:'FIELD',
    effect:{type:'STAT_LOWER',stat:'spd',stages:1}, description:'Sticky silk threads slow the foe.' },
  CARAPACE_SHIELD: { id:'CARAPACE_SHIELD', name:'Carapace Shield', type:'BUG', category:'STATUS', power:0, accuracy:100, pp:15, priority:0, animStyle:'SELF',
    effect:{type:'STAT_RAISE',stat:'def',stages:2}, description:'Hardens the carapace, sharply raising Defense.' },
  BUG_PULSE: { id:'BUG_PULSE', name:'Bug Pulse', type:'BUG', category:'SPECIAL', power:65, accuracy:100, pp:15, priority:0, animStyle:'PULSE',
    effect:{type:'NONE'}, description:'Pulses of insect sonic energy hit the foe.' },
  WING_CUT: { id:'WING_CUT', name:'Wing Cut', type:'BUG', category:'PHYSICAL', power:60, accuracy:100, pp:20, priority:0, animStyle:'MELEE',
    effect:{type:'NONE'}, description:'A precise cut with razor-sharp wings.' },
  COCOON_SLAM: { id:'COCOON_SLAM', name:'Cocoon Slam', type:'BUG', category:'PHYSICAL', power:75, accuracy:100, pp:15, priority:0, animStyle:'SLAM',
    effect:{type:'NONE'}, description:'Slams with a hardened cocoon shell.' },
  BUG_BEAM: { id:'BUG_BEAM', name:'Bug Beam', type:'BUG', category:'SPECIAL', power:80, accuracy:100, pp:10, priority:0, animStyle:'BEAM',
    effect:{type:'NONE'}, description:'A beam of concentrated insect sonic energy.' },
  VENOM_STING_PLUS: { id:'VENOM_STING_PLUS', name:'Venom Sting', type:'BUG', category:'PHYSICAL', power:55, accuracy:100, pp:20, priority:0, animStyle:'PROJECTILE',
    effect:{type:'POISON_CHANCE',chance:50}, description:'A highly venomous sting likely to poison.' },
  BUG_AURA: { id:'BUG_AURA', name:'Swarm Aura', type:'BUG', category:'STATUS', power:0, accuracy:100, pp:15, priority:0, animStyle:'AURA',
    effect:{type:'STAT_RAISE',stat:'atk',stages:2}, description:'Channels swarm power, sharply raising Attack.' },
  ARMOR_SLASH: { id:'ARMOR_SLASH', name:'Armor Slash', type:'BUG', category:'PHYSICAL', power:70, accuracy:100, pp:15, priority:0, animStyle:'MELEE',
    effect:{type:'STAT_LOWER',stat:'def',stages:1}, description:'Slashes with an armored limb, lowering Defense.' },
  HIVE_MIND: { id:'HIVE_MIND', name:'Hive Mind', type:'BUG', category:'STATUS', power:0, accuracy:100, pp:10, priority:0, animStyle:'SELF',
    effect:{type:'STAT_RAISE',stats:['atk','spAtk'],stages:1}, description:'The hive mind boosts both attack stats.' },
  ANTENNA_WAVE: { id:'ANTENNA_WAVE', name:'Antenna Wave', type:'BUG', category:'SPECIAL', power:60, accuracy:100, pp:20, priority:0, animStyle:'WAVE',
    effect:{type:'PARALYSIS',chance:20}, description:'Antenna-generated waves may paralyze.' },
  CHITINOUS_BASH: { id:'CHITINOUS_BASH', name:'Chitinous Bash', type:'BUG', category:'PHYSICAL', power:90, accuracy:95, pp:10, priority:0, animStyle:'SLAM',
    effect:{type:'NONE'}, description:'Bashes with an extremely tough chitinous body.' },
  MOLT_STRIKE: { id:'MOLT_STRIKE', name:'Molt Strike', type:'BUG', category:'PHYSICAL', power:65, accuracy:100, pp:15, priority:0, animStyle:'MELEE',
    effect:{type:'STAT_RAISE',stat:'spd',stages:1}, description:'Molts to reveal a swift new body, boosting Speed.' },
  PHEROMONE: { id:'PHEROMONE', name:'Pheromone', type:'BUG', category:'STATUS', power:0, accuracy:100, pp:20, priority:0, animStyle:'FIELD',
    effect:{type:'STAT_LOWER',stat:'atk',stages:2}, description:'Releases pheromones that sharply lower Attack.' },
  BUG_SLAM: { id:'BUG_SLAM', name:'Bug Slam', type:'BUG', category:'PHYSICAL', power:85, accuracy:95, pp:10, priority:0, animStyle:'SLAM',
    effect:{type:'NONE'}, description:'A slamming attack from a hardened insect body.' },
  LARVA_BLAST: { id:'LARVA_BLAST', name:'Larva Blast', type:'BUG', category:'SPECIAL', power:75, accuracy:100, pp:15, priority:0, animStyle:'PROJECTILE',
    effect:{type:'POISON_CHANCE',chance:20}, description:'Blasts corrosive larval fluid that may poison.' },
  EXOSKELETON: { id:'EXOSKELETON', name:'Exoskeleton', type:'BUG', category:'STATUS', power:0, accuracy:100, pp:10, priority:0, animStyle:'SELF',
    effect:{type:'STAT_RAISE',stats:['def','spDef'],stages:1}, description:'Hardens the exoskeleton, boosting both defenses.' },
  SWARM_PULSE: { id:'SWARM_PULSE', name:'Swarm Pulse', type:'BUG', category:'SPECIAL', power:80, accuracy:100, pp:10, priority:0, animStyle:'PULSE',
    effect:{type:'NONE'}, description:'The unified pulse of an entire swarm.' },
`;

// Filter and insert
const blocks = newMoves.split(/\n  (?=[A-Z_0-9]+:\s*\{)/).filter(b => {
  const m = b.match(/^([A-Z_0-9]+):/);
  return m && !existing.has(m[1]);
});

console.log('New moves to add:', blocks.length);

const insertPos = src.lastIndexOf('\n};');
if (insertPos === -1) { console.error('Could not find insertion point'); process.exit(1); }

const toInsert = '\n' + blocks.join('\n  ') + '\n';
const newSrc = src.slice(0, insertPos) + toInsert + src.slice(insertPos);

fs.writeFileSync('./js/data/moves.js', newSrc, 'utf8');
console.log('Done! moves.js updated.');
