/**
 * add_moves_p2a.js — Phase 2 Batch A
 * Adds ~250 new moves (types: FIRE, WATER, GRASS, ELECTRIC, ICE, NORMAL, FIGHTING, POISON, GROUND, FLYING)
 * Each move has unique animStyle. Target: 496 + 250 = 746 total.
 */
const fs = require('fs');
const src = fs.readFileSync('./js/data/moves.js', 'utf8');
const existing = new Set([...src.matchAll(/^\s{2}([A-Z_0-9]+):\s*\{/gm)].map(m => m[1]).filter(id => id !== 'DG'));
console.log('Existing moves:', existing.size);

const newMoves = `
  // ═══════════════════════════════════════════════════════
  // PHASE 2 BATCH A — FIRE (25 new)
  // ═══════════════════════════════════════════════════════
  LAVA_SURGE: { id:'LAVA_SURGE', name:'Lava Surge', type:'FIRE', category:'SPECIAL', power:85, accuracy:90, pp:10, priority:0, animStyle:'BURST',
    effect:{type:'BURN_CHANCE',chance:30}, description:'A surge of lava erupts upward. May burn the foe.' },
  FIRE_WHEEL: { id:'FIRE_WHEEL', name:'Fire Wheel', type:'FIRE', category:'PHYSICAL', power:70, accuracy:100, pp:15, priority:0, animStyle:'ARC',
    effect:{type:'NONE'}, description:'The user rolls into the foe wrapped in flames.' },
  MAGMA_RAIN: { id:'MAGMA_RAIN', name:'Magma Rain', type:'FIRE', category:'SPECIAL', power:90, accuracy:85, pp:10, priority:0, animStyle:'MULTI',
    effect:{type:'BURN_CHANCE',chance:20}, description:'Molten rock rains down on all foes. May burn.' },
  EMBER_STORM: { id:'EMBER_STORM', name:'Ember Storm', type:'FIRE', category:'SPECIAL', power:60, accuracy:100, pp:20, priority:0, animStyle:'VORTEX',
    effect:{type:'BURN_CHANCE',chance:15}, description:'A swirling storm of embers engulfs the foe.' },
  SCORCHING_BREATH: { id:'SCORCHING_BREATH', name:'Scorching Breath', type:'FIRE', category:'SPECIAL', power:75, accuracy:95, pp:15, priority:0, animStyle:'CONE',
    effect:{type:'BURN_CHANCE',chance:25}, description:'Searing breath scorches the foe. May cause a burn.' },
  INFERNO_DIVE: { id:'INFERNO_DIVE', name:'Inferno Dive', type:'FIRE', category:'PHYSICAL', power:100, accuracy:90, pp:10, priority:0, animStyle:'SLAM',
    effect:{type:'RECOIL',fraction:25}, description:'The user dives into the foe in a blazing spiral. User takes recoil.' },
  VOLCANIC_ASH: { id:'VOLCANIC_ASH', name:'Volcanic Ash', type:'FIRE', category:'STATUS', power:0, accuracy:90, pp:20, priority:0, animStyle:'FIELD',
    effect:{type:'STAT_LOWER',stat:'acc',stages:1}, description:'Ash clouds lower the foe\'s accuracy.' },
  EMBER_CLAW: { id:'EMBER_CLAW', name:'Ember Claw', type:'FIRE', category:'PHYSICAL', power:55, accuracy:100, pp:20, priority:0, animStyle:'MELEE',
    effect:{type:'BURN_CHANCE',chance:20}, description:'Claws blazing with fire slash the foe.' },
  LAVA_PLUNGE: { id:'LAVA_PLUNGE', name:'Lava Plunge', type:'FIRE', category:'PHYSICAL', power:110, accuracy:85, pp:8, priority:0, animStyle:'SLAM',
    effect:{type:'NONE'}, description:'The user plunges into lava and slams the foe with burning force.' },
  HEAT_LANCE: { id:'HEAT_LANCE', name:'Heat Lance', type:'FIRE', category:'SPECIAL', power:80, accuracy:100, pp:10, priority:0, animStyle:'BEAM',
    effect:{type:'NONE'}, description:'A thin beam of superheated plasma pierces the foe.' },
  CHAR_PULSE: { id:'CHAR_PULSE', name:'Char Pulse', type:'FIRE', category:'SPECIAL', power:65, accuracy:100, pp:15, priority:0, animStyle:'PULSE',
    effect:{type:'BURN_CHANCE',chance:10}, description:'A pulse of charring energy radiates outward.' },
  MAGMA_FIST: { id:'MAGMA_FIST', name:'Magma Fist', type:'FIRE', category:'PHYSICAL', power:85, accuracy:95, pp:10, priority:0, animStyle:'MELEE',
    effect:{type:'BURN_CHANCE',chance:30}, description:'A punch wrapped in magma scorches on impact.' },
  SOLAR_FLARE: { id:'SOLAR_FLARE', name:'Solar Flare', type:'FIRE', category:'SPECIAL', power:120, accuracy:80, pp:8, priority:0, animStyle:'BURST',
    effect:{type:'STAT_LOWER',stat:'spDef',stages:1}, description:'A blinding solar burst scalds and lowers Sp. Def.' },
  FIREWORKS: { id:'FIREWORKS', name:'Fireworks', type:'FIRE', category:'SPECIAL', power:50, accuracy:100, pp:20, priority:0, animStyle:'MULTI',
    effect:{type:'MULTI_HIT',hits:'2-5'}, description:'Colorful fire bursts strike 2-5 times.' },
  BURNING_COMET: { id:'BURNING_COMET', name:'Burning Comet', type:'FIRE', category:'SPECIAL', power:100, accuracy:90, pp:10, priority:0, animStyle:'PROJECTILE',
    effect:{type:'BURN_CHANCE',chance:20}, description:'A blazing comet of condensed fire crashes down.' },
  IMMOLATION: { id:'IMMOLATION', name:'Immolation', type:'FIRE', category:'SPECIAL', power:0, accuracy:100, pp:10, priority:0, animStyle:'AURA',
    effect:{type:'STAT_RAISE',stat:'spAtk',stages:3}, description:'The user ignites its own aura, sharply boosting Sp. Atk.' },
  CINDERBLAST: { id:'CINDERBLAST', name:'Cinderblast', type:'FIRE', category:'SPECIAL', power:90, accuracy:100, pp:10, priority:0, animStyle:'BURST',
    effect:{type:'NONE'}, description:'An explosion of cinder and flame erupts at the foe.' },
  SMOLDER: { id:'SMOLDER', name:'Smolder', type:'FIRE', category:'STATUS', power:0, accuracy:100, pp:30, priority:0, animStyle:'FIELD',
    effect:{type:'BURN_CHANCE',chance:100}, description:'Sets the foe ablaze with a steady, persistent flame.' },
  FIRE_SURGE: { id:'FIRE_SURGE', name:'Fire Surge', type:'FIRE', category:'SPECIAL', power:75, accuracy:100, pp:15, priority:0, animStyle:'WAVE',
    effect:{type:'NONE'}, description:'A surging wall of flames sweeps over the foe.' },
  FIRECRACKER: { id:'FIRECRACKER', name:'Firecracker', type:'FIRE', category:'PHYSICAL', power:45, accuracy:100, pp:25, priority:1, animStyle:'PROJECTILE',
    effect:{type:'FLINCH',chance:20}, description:'A fast-flying ember may make the foe flinch.' },
  MAGMA_SHIELD: { id:'MAGMA_SHIELD', name:'Magma Shield', type:'FIRE', category:'STATUS', power:0, accuracy:100, pp:15, priority:0, animStyle:'SELF',
    effect:{type:'STAT_RAISE',stat:'def',stages:2}, description:'Coats the body in magma to raise Defense.' },
  FLAME_TORNADO: { id:'FLAME_TORNADO', name:'Flame Tornado', type:'FIRE', category:'SPECIAL', power:95, accuracy:85, pp:10, priority:0, animStyle:'VORTEX',
    effect:{type:'BURN_CHANCE',chance:30}, description:'A spinning funnel of fire traps the foe.' },
  BONFIRE: { id:'BONFIRE', name:'Bonfire', type:'FIRE', category:'SPECIAL', power:70, accuracy:100, pp:15, priority:0, animStyle:'BURST',
    effect:{type:'STAT_RAISE',stat:'spAtk',stages:1}, description:'The user basks in a bonfire, boosting Sp. Atk.' },
  IGNITE: { id:'IGNITE', name:'Ignite', type:'FIRE', category:'STATUS', power:0, accuracy:95, pp:20, priority:0, animStyle:'FIELD',
    effect:{type:'STAT_LOWER',stat:'spDef',stages:1}, description:'Sets fire to the foe\'s defenses, lowering Sp. Def.' },
  PYRE_WAVE: { id:'PYRE_WAVE', name:'Pyre Wave', type:'FIRE', category:'SPECIAL', power:80, accuracy:95, pp:10, priority:0, animStyle:'WAVE',
    effect:{type:'BURN_CHANCE',chance:25}, description:'A wave of funeral fire rolls over the battlefield.' },

  // ═══════════════════════════════════════════════════════
  // PHASE 2 BATCH A — WATER (25 new)
  // ═══════════════════════════════════════════════════════
  TORRENT_RUSH: { id:'TORRENT_RUSH', name:'Torrent Rush', type:'WATER', category:'PHYSICAL', power:90, accuracy:95, pp:10, priority:0, animStyle:'WAVE',
    effect:{type:'NONE'}, description:'The user rushes at the foe on a powerful torrent.' },
  MIST_VEIL: { id:'MIST_VEIL', name:'Mist Veil', type:'WATER', category:'STATUS', power:0, accuracy:100, pp:20, priority:0, animStyle:'SELF',
    effect:{type:'STAT_RAISE',stat:'def',stages:1}, description:'Wraps the user in a defensive mist.' },
  SEAFOAM_BLAST: { id:'SEAFOAM_BLAST', name:'Seafoam Blast', type:'WATER', category:'SPECIAL', power:65, accuracy:100, pp:20, priority:0, animStyle:'BURST',
    effect:{type:'STAT_LOWER',stat:'spDef',stages:1}, description:'Blasts with seafoam that eats at defenses.' },
  PRESSURE_STREAM: { id:'PRESSURE_STREAM', name:'Pressure Stream', type:'WATER', category:'SPECIAL', power:80, accuracy:100, pp:15, priority:0, animStyle:'BEAM',
    effect:{type:'NONE'}, description:'High-pressure water cuts with pinpoint accuracy.' },
  RIPTIDE: { id:'RIPTIDE', name:'Riptide', type:'WATER', category:'PHYSICAL', power:85, accuracy:95, pp:10, priority:0, animStyle:'WAVE',
    effect:{type:'NONE'}, description:'A sudden rip current drags the foe under.' },
  AQUA_SPIKE: { id:'AQUA_SPIKE', name:'Aqua Spike', type:'WATER', category:'PHYSICAL', power:60, accuracy:100, pp:20, priority:0, animStyle:'PROJECTILE',
    effect:{type:'NONE'}, description:'Sharp spikes of compressed water pierce the foe.' },
  DEEP_CURRENT: { id:'DEEP_CURRENT', name:'Deep Current', type:'WATER', category:'SPECIAL', power:95, accuracy:90, pp:10, priority:0, animStyle:'VORTEX',
    effect:{type:'NONE'}, description:'A deep ocean current spirals around the foe.' },
  GEYSER: { id:'GEYSER', name:'Geyser', type:'WATER', category:'SPECIAL', power:110, accuracy:85, pp:8, priority:0, animStyle:'BURST',
    effect:{type:'NONE'}, description:'A superheated geyser erupts beneath the foe.' },
  BUBBLE_BOMB: { id:'BUBBLE_BOMB', name:'Bubble Bomb', type:'WATER', category:'SPECIAL', power:55, accuracy:100, pp:20, priority:0, animStyle:'PROJECTILE',
    effect:{type:'STAT_LOWER',stat:'spd',stages:1}, description:'Exploding bubbles slow the foe.' },
  GLACIER_WALL: { id:'GLACIER_WALL', name:'Glacier Wall', type:'WATER', category:'STATUS', power:0, accuracy:100, pp:15, priority:0, animStyle:'SELF',
    effect:{type:'STAT_RAISE',stat:'def',stages:2}, description:'Forms an icy wall of glacial water around the user.' },
  MAELSTROM: { id:'MAELSTROM', name:'Maelstrom', type:'WATER', category:'SPECIAL', power:100, accuracy:85, pp:10, priority:0, animStyle:'VORTEX',
    effect:{type:'NONE'}, description:'A violent whirlpool traps and batters the foe.' },
  CREST_WAVE: { id:'CREST_WAVE', name:'Crest Wave', type:'WATER', category:'SPECIAL', power:70, accuracy:100, pp:15, priority:0, animStyle:'WAVE',
    effect:{type:'NONE'}, description:'A cresting tidal wave washes over the foe.' },
  HYDRO_BLADE: { id:'HYDRO_BLADE', name:'Hydro Blade', type:'WATER', category:'PHYSICAL', power:85, accuracy:100, pp:10, priority:0, animStyle:'MELEE',
    effect:{type:'NONE'}, description:'A blade of pressurized water slashes cleanly.' },
  OCEAN_PULSE: { id:'OCEAN_PULSE', name:'Ocean Pulse', type:'WATER', category:'SPECIAL', power:75, accuracy:100, pp:15, priority:0, animStyle:'PULSE',
    effect:{type:'NONE'}, description:'Rhythmic pulses of ocean energy buffet the foe.' },
  WATER_SPEAR: { id:'WATER_SPEAR', name:'Water Spear', type:'WATER', category:'PHYSICAL', power:65, accuracy:100, pp:20, priority:0, animStyle:'PROJECTILE',
    effect:{type:'NONE'}, description:'A sharpened spike of water hurled at speed.' },
  TIDAL_WAVE: { id:'TIDAL_WAVE', name:'Tidal Wave', type:'WATER', category:'SPECIAL', power:120, accuracy:80, pp:5, priority:0, animStyle:'WAVE',
    effect:{type:'NONE'}, description:'A massive tidal wave crashes across the field.' },
  SALTWATER_SURGE: { id:'SALTWATER_SURGE', name:'Saltwater Surge', type:'WATER', category:'SPECIAL', power:70, accuracy:100, pp:15, priority:0, animStyle:'BURST',
    effect:{type:'BURN_CHANCE',chance:10}, description:'Stinging saltwater blasts sting like fire.' },
  AQUA_BURST: { id:'AQUA_BURST', name:'Aqua Burst', type:'WATER', category:'SPECIAL', power:80, accuracy:100, pp:10, priority:0, animStyle:'BURST',
    effect:{type:'NONE'}, description:'An explosive burst of water detonates on contact.' },
  SPRAY_STORM: { id:'SPRAY_STORM', name:'Spray Storm', type:'WATER', category:'SPECIAL', power:55, accuracy:95, pp:20, priority:0, animStyle:'MULTI',
    effect:{type:'MULTI_HIT',hits:'2-5'}, description:'A storm of water droplets strikes 2-5 times.' },
  POOL_CRASH: { id:'POOL_CRASH', name:'Pool Crash', type:'WATER', category:'PHYSICAL', power:100, accuracy:90, pp:10, priority:0, animStyle:'SLAM',
    effect:{type:'RECOIL',fraction:25}, description:'Crashes the foe into a pool of water. Causes recoil.' },
  FOG_SCREEN: { id:'FOG_SCREEN', name:'Fog Screen', type:'WATER', category:'STATUS', power:0, accuracy:100, pp:20, priority:0, animStyle:'FIELD',
    effect:{type:'STAT_LOWER',stat:'acc',stages:1}, description:'Thick fog reduces the foe\'s accuracy.' },
  WATER_FANG: { id:'WATER_FANG', name:'Water Fang', type:'WATER', category:'PHYSICAL', power:65, accuracy:95, pp:15, priority:0, animStyle:'MELEE',
    effect:{type:'PARALYSIS',chance:10}, description:'Watery fangs may paralyze on impact.' },
  UNDERTOW: { id:'UNDERTOW', name:'Undertow', type:'WATER', category:'SPECIAL', power:75, accuracy:100, pp:15, priority:0, animStyle:'WAVE',
    effect:{type:'STAT_LOWER',stat:'spd',stages:1}, description:'A dragging current slows the foe.' },
  FROZEN_TIDE: { id:'FROZEN_TIDE', name:'Frozen Tide', type:'WATER', category:'SPECIAL', power:85, accuracy:90, pp:10, priority:0, animStyle:'WAVE',
    effect:{type:'FREEZE_CHANCE',chance:10}, description:'Supercooled tidal water may freeze the foe.' },
  RIVER_RUSH: { id:'RIVER_RUSH', name:'River Rush', type:'WATER', category:'PHYSICAL', power:70, accuracy:100, pp:15, priority:1, animStyle:'WAVE',
    effect:{type:'NONE'}, description:'The user surges like a river, striking first.' },

  // ═══════════════════════════════════════════════════════
  // PHASE 2 BATCH A — GRASS (25 new)
  // ═══════════════════════════════════════════════════════
  THORN_VOLLEY: { id:'THORN_VOLLEY', name:'Thorn Volley', type:'GRASS', category:'PHYSICAL', power:55, accuracy:95, pp:20, priority:0, animStyle:'MULTI',
    effect:{type:'MULTI_HIT',hits:'2-5'}, description:'A volley of razor thorns strikes 2-5 times.' },
  VERDANT_SURGE: { id:'VERDANT_SURGE', name:'Verdant Surge', type:'GRASS', category:'SPECIAL', power:80, accuracy:100, pp:15, priority:0, animStyle:'WAVE',
    effect:{type:'NONE'}, description:'A surge of verdant energy rolls over the battlefield.' },
  CANOPY_CRASH: { id:'CANOPY_CRASH', name:'Canopy Crash', type:'GRASS', category:'PHYSICAL', power:100, accuracy:90, pp:10, priority:0, animStyle:'SLAM',
    effect:{type:'NONE'}, description:'The user crashes down from the treetop canopy.' },
  SPORE_CLOUD: { id:'SPORE_CLOUD', name:'Spore Cloud', type:'GRASS', category:'STATUS', power:0, accuracy:90, pp:15, priority:0, animStyle:'FIELD',
    effect:{type:'SLEEP',chance:100}, description:'A dense cloud of sleep spores settles on the foe.' },
  VINE_LASH: { id:'VINE_LASH', name:'Vine Lash', type:'GRASS', category:'PHYSICAL', power:75, accuracy:100, pp:15, priority:0, animStyle:'MELEE',
    effect:{type:'NONE'}, description:'Whipping vines snap at the foe with great force.' },
  PHOTON_LEAF: { id:'PHOTON_LEAF', name:'Photon Leaf', type:'GRASS', category:'SPECIAL', power:85, accuracy:100, pp:10, priority:0, animStyle:'PULSE',
    effect:{type:'NONE'}, description:'Leaves charged with solar energy blast the foe.' },
  ROOT_BIND: { id:'ROOT_BIND', name:'Root Bind', type:'GRASS', category:'STATUS', power:0, accuracy:90, pp:20, priority:0, animStyle:'FIELD',
    effect:{type:'PARALYSIS',chance:100}, description:'Underground roots burst up and bind the foe.' },
  BLOOM_BURST: { id:'BLOOM_BURST', name:'Bloom Burst', type:'GRASS', category:'SPECIAL', power:65, accuracy:100, pp:20, priority:0, animStyle:'BURST',
    effect:{type:'STAT_LOWER',stat:'spDef',stages:1}, description:'Pollen bursts lower the foe\'s Sp. Def.' },
  JUNGLE_PULSE: { id:'JUNGLE_PULSE', name:'Jungle Pulse', type:'GRASS', category:'SPECIAL', power:70, accuracy:100, pp:15, priority:0, animStyle:'PULSE',
    effect:{type:'NONE'}, description:'Energy from the jungle floor pulses into the foe.' },
  BRAMBLE_BASH: { id:'BRAMBLE_BASH', name:'Bramble Bash', type:'GRASS', category:'PHYSICAL', power:80, accuracy:95, pp:10, priority:0, animStyle:'SLAM',
    effect:{type:'FLINCH',chance:20}, description:'A slam with thorny brambles may cause flinching.' },
  GRASS_KNOT_STRONG: { id:'GRASS_KNOT_STRONG', name:'Grass Bind', type:'GRASS', category:'SPECIAL', power:90, accuracy:100, pp:10, priority:0, animStyle:'MELEE',
    effect:{type:'NONE'}, description:'Grass coils crush the foe; more effective on heavier foes.' },
  FERN_WAVE: { id:'FERN_WAVE', name:'Fern Wave', type:'GRASS', category:'SPECIAL', power:60, accuracy:100, pp:20, priority:0, animStyle:'WAVE',
    effect:{type:'NONE'}, description:'A rippling wave of fern energy washes over the foe.' },
  OVERGROWTH: { id:'OVERGROWTH', name:'Overgrowth', type:'GRASS', category:'STATUS', power:0, accuracy:100, pp:10, priority:0, animStyle:'SELF',
    effect:{type:'STAT_RAISE',stat:'spAtk',stages:2}, description:'Taps into Overgrowth, sharply raising Sp. Atk.' },
  FOREST_FURY: { id:'FOREST_FURY', name:'Forest Fury', type:'GRASS', category:'PHYSICAL', power:110, accuracy:85, pp:8, priority:0, animStyle:'BURST',
    effect:{type:'RECOIL',fraction:33}, description:'Channels the fury of the forest. Takes recoil.' },
  LEAF_TORNADO: { id:'LEAF_TORNADO', name:'Leaf Tornado', type:'GRASS', category:'SPECIAL', power:65, accuracy:90, pp:15, priority:0, animStyle:'VORTEX',
    effect:{type:'STAT_LOWER',stat:'acc',stages:1}, description:'A vortex of leaves may reduce accuracy.' },
  PHOTOSYNTHESIS: { id:'PHOTOSYNTHESIS', name:'Photosynthesis', type:'GRASS', category:'STATUS', power:0, accuracy:100, pp:10, priority:0, animStyle:'SELF',
    effect:{type:'HEAL',fraction:50}, description:'The user absorbs sunlight to restore half its HP.' },
  WOOD_HAMMER: { id:'WOOD_HAMMER', name:'Wood Hammer', type:'GRASS', category:'PHYSICAL', power:120, accuracy:100, pp:10, priority:0, animStyle:'SLAM',
    effect:{type:'RECOIL',fraction:33}, description:'The user slams with a hardened wooden limb.' },
  SEED_CANNON: { id:'SEED_CANNON', name:'Seed Cannon', type:'GRASS', category:'PHYSICAL', power:70, accuracy:100, pp:15, priority:0, animStyle:'PROJECTILE',
    effect:{type:'NONE'}, description:'Explosive seeds fired at high velocity.' },
  CHLORO_BURST: { id:'CHLORO_BURST', name:'Chloro Burst', type:'GRASS', category:'SPECIAL', power:75, accuracy:100, pp:15, priority:0, animStyle:'BURST',
    effect:{type:'NONE'}, description:'Chlorophyll energy explodes outward from the user.' },
  BARK_SHIELD: { id:'BARK_SHIELD', name:'Bark Shield', type:'GRASS', category:'STATUS', power:0, accuracy:100, pp:20, priority:0, animStyle:'SELF',
    effect:{type:'STAT_RAISE',stat:'def',stages:2}, description:'Hardens a bark shell around the body, raising Defense.' },
  VINE_DRAIN: { id:'VINE_DRAIN', name:'Vine Drain', type:'GRASS', category:'SPECIAL', power:75, accuracy:100, pp:10, priority:0, animStyle:'DRAIN',
    effect:{type:'DRAIN',fraction:50}, description:'Vines drain life from the foe, healing the user.' },
  PETAL_STORM: { id:'PETAL_STORM', name:'Petal Storm', type:'GRASS', category:'PHYSICAL', power:90, accuracy:100, pp:15, priority:0, animStyle:'VORTEX',
    effect:{type:'NONE'}, description:'Razor-edged petals whirl in a violent storm.' },
  SAP_DRAIN: { id:'SAP_DRAIN', name:'Sap Drain', type:'GRASS', category:'SPECIAL', power:55, accuracy:100, pp:20, priority:0, animStyle:'DRAIN',
    effect:{type:'DRAIN',fraction:50}, description:'Draws vital sap from the foe to heal the user.' },
  TANGLE_SHOT: { id:'TANGLE_SHOT', name:'Tangle Shot', type:'GRASS', category:'PHYSICAL', power:50, accuracy:100, pp:20, priority:0, animStyle:'PROJECTILE',
    effect:{type:'STAT_LOWER',stat:'spd',stages:1}, description:'Sticky vine tangles slow the foe.' },
  NATURE_POWER: { id:'NATURE_POWER', name:'Nature\'s Wrath', type:'GRASS', category:'SPECIAL', power:100, accuracy:90, pp:10, priority:0, animStyle:'BURST',
    effect:{type:'NONE'}, description:'Channels the full wrath of nature into an attack.' },

  // ═══════════════════════════════════════════════════════
  // PHASE 2 BATCH A — ELECTRIC (25 new)
  // ═══════════════════════════════════════════════════════
  VOLTAGE_CRASH: { id:'VOLTAGE_CRASH', name:'Voltage Crash', type:'ELECTRIC', category:'PHYSICAL', power:90, accuracy:95, pp:10, priority:0, animStyle:'SLAM',
    effect:{type:'PARALYSIS',chance:20}, description:'Crashes into the foe with electrified body.' },
  CHAIN_LIGHTNING: { id:'CHAIN_LIGHTNING', name:'Chain Lightning', type:'ELECTRIC', category:'SPECIAL', power:70, accuracy:100, pp:15, priority:0, animStyle:'MULTI',
    effect:{type:'PARALYSIS',chance:30}, description:'Lightning chains across multiple targets.' },
  THUNDER_CLAP: { id:'THUNDER_CLAP', name:'Thunder Clap', type:'ELECTRIC', category:'SPECIAL', power:80, accuracy:100, pp:10, priority:0, animStyle:'BURST',
    effect:{type:'FLINCH',chance:20}, description:'A deafening thunderclap may cause flinching.' },
  PLASMA_BURST: { id:'PLASMA_BURST', name:'Plasma Burst', type:'ELECTRIC', category:'SPECIAL', power:85, accuracy:95, pp:10, priority:0, animStyle:'BURST',
    effect:{type:'PARALYSIS',chance:20}, description:'Superheated plasma bursts around the foe.' },
  STATIC_FIELD: { id:'STATIC_FIELD', name:'Static Field', type:'ELECTRIC', category:'STATUS', power:0, accuracy:100, pp:20, priority:0, animStyle:'FIELD',
    effect:{type:'PARALYSIS',chance:100}, description:'Creates a static field that paralyzes the foe.' },
  SPARK_SHOWER: { id:'SPARK_SHOWER', name:'Spark Shower', type:'ELECTRIC', category:'SPECIAL', power:55, accuracy:100, pp:20, priority:0, animStyle:'MULTI',
    effect:{type:'PARALYSIS',chance:10}, description:'A shower of sparks strikes 2-5 times.' },
  ELECTROMAGNETIC: { id:'ELECTROMAGNETIC', name:'Electromagnetic', type:'ELECTRIC', category:'STATUS', power:0, accuracy:100, pp:15, priority:0, animStyle:'FIELD',
    effect:{type:'STAT_LOWER',stat:'spd',stages:2}, description:'An EM pulse sharply slows the foe.' },
  THUNDER_FIST: { id:'THUNDER_FIST', name:'Thunder Fist', type:'ELECTRIC', category:'PHYSICAL', power:85, accuracy:100, pp:10, priority:0, animStyle:'MELEE',
    effect:{type:'PARALYSIS',chance:30}, description:'An electrified punch that may cause paralysis.' },
  GALVANIC_STRIKE: { id:'GALVANIC_STRIKE', name:'Galvanic Strike', type:'ELECTRIC', category:'PHYSICAL', power:75, accuracy:100, pp:15, priority:0, animStyle:'MELEE',
    effect:{type:'NONE'}, description:'A powerful strike channeling galvanic energy.' },
  VOLT_CRASH: { id:'VOLT_CRASH', name:'Volt Crash', type:'ELECTRIC', category:'PHYSICAL', power:100, accuracy:90, pp:10, priority:0, animStyle:'SLAM',
    effect:{type:'PARALYSIS',chance:30}, description:'Crashes with massive electrical voltage.' },
  ARC_FLASH: { id:'ARC_FLASH', name:'Arc Flash', type:'ELECTRIC', category:'SPECIAL', power:60, accuracy:100, pp:20, priority:0, animStyle:'ARC',
    effect:{type:'PARALYSIS',chance:30}, description:'A bright arc of electricity may paralyze.' },
  ELECTRON_BEAM: { id:'ELECTRON_BEAM', name:'Electron Beam', type:'ELECTRIC', category:'SPECIAL', power:130, accuracy:100, pp:5, priority:0, animStyle:'BEAM',
    effect:{type:'STAT_LOWER',stat:'spAtk',stages:2}, description:'Full-power electron beam lowers the user\'s Sp. Atk.' },
  THUNDER_CAGE: { id:'THUNDER_CAGE', name:'Thunder Cage', type:'ELECTRIC', category:'SPECIAL', power:80, accuracy:90, pp:10, priority:0, animStyle:'VORTEX',
    effect:{type:'PARALYSIS',chance:100}, description:'Traps the foe in a cage of lightning bolts.' },
  POWER_SURGE: { id:'POWER_SURGE', name:'Power Surge', type:'ELECTRIC', category:'STATUS', power:0, accuracy:100, pp:15, priority:0, animStyle:'SELF',
    effect:{type:'STAT_RAISE',stat:'spAtk',stages:2}, description:'The user overloads, sharply boosting Sp. Atk.' },
  BOLT_STRIKE: { id:'BOLT_STRIKE', name:'Bolt Strike', type:'ELECTRIC', category:'PHYSICAL', power:130, accuracy:85, pp:5, priority:0, animStyle:'BEAM',
    effect:{type:'PARALYSIS',chance:20}, description:'A lightning-speed strike of immense power.' },
  MAGNETIC_PULSE: { id:'MAGNETIC_PULSE', name:'Magnetic Pulse', type:'ELECTRIC', category:'SPECIAL', power:70, accuracy:100, pp:15, priority:0, animStyle:'PULSE',
    effect:{type:'STAT_LOWER',stat:'def',stages:1}, description:'Magnetic waves disrupt the foe\'s defenses.' },
  TESLA_BLAST: { id:'TESLA_BLAST', name:'Tesla Blast', type:'ELECTRIC', category:'SPECIAL', power:90, accuracy:95, pp:10, priority:0, animStyle:'BURST',
    effect:{type:'PARALYSIS',chance:20}, description:'A blast of Tesla-coil electricity shocks the foe.' },
  SHOCK_WAVE_SURGE: { id:'SHOCK_WAVE_SURGE', name:'Shock Surge', type:'ELECTRIC', category:'SPECIAL', power:75, accuracy:100, pp:15, priority:0, animStyle:'WAVE',
    effect:{type:'NONE'}, description:'A shockwave of electricity pulses outward.' },
  LIGHTNING_ROD_HIT: { id:'LIGHTNING_ROD_HIT', name:'Lightning Spear', type:'ELECTRIC', category:'PHYSICAL', power:80, accuracy:100, pp:10, priority:0, animStyle:'BEAM',
    effect:{type:'NONE'}, description:'A concentrated lightning bolt hurled like a spear.' },
  OVERCHARGE: { id:'OVERCHARGE', name:'Overcharge', type:'ELECTRIC', category:'SPECIAL', power:110, accuracy:90, pp:8, priority:0, animStyle:'BURST',
    effect:{type:'RECOIL',fraction:25}, description:'Dangerously overcharges for massive damage. Causes recoil.' },
  ZAP_BURST: { id:'ZAP_BURST', name:'Zap Burst', type:'ELECTRIC', category:'SPECIAL', power:50, accuracy:100, pp:25, priority:0, animStyle:'BURST',
    effect:{type:'PARALYSIS',chance:20}, description:'Quick zap of electricity. May paralyze.' },
  STORMFRONT: { id:'STORMFRONT', name:'Stormfront', type:'ELECTRIC', category:'SPECIAL', power:95, accuracy:90, pp:10, priority:0, animStyle:'VORTEX',
    effect:{type:'PARALYSIS',chance:30}, description:'Summons a storm front that electrifies the field.' },
  CHARGE_STRIKE: { id:'CHARGE_STRIKE', name:'Charge Strike', type:'ELECTRIC', category:'PHYSICAL', power:65, accuracy:100, pp:15, priority:0, animStyle:'MELEE',
    effect:{type:'STAT_RAISE',stat:'spDef',stages:1}, description:'Charges up and strikes, boosting Sp. Def.' },
  NEON_BURST: { id:'NEON_BURST', name:'Neon Burst', type:'ELECTRIC', category:'SPECIAL', power:80, accuracy:100, pp:10, priority:0, animStyle:'BURST',
    effect:{type:'NONE'}, description:'Neon-lit energy detonates in a brilliant flash.' },
  SPARK_TRAIL: { id:'SPARK_TRAIL', name:'Spark Trail', type:'ELECTRIC', category:'PHYSICAL', power:60, accuracy:100, pp:20, priority:0, animStyle:'ARC',
    effect:{type:'PARALYSIS',chance:20}, description:'Leaves a trail of sparks that shocks the foe.' },

  // ═══════════════════════════════════════════════════════
  // PHASE 2 BATCH A — ICE (20 new)
  // ═══════════════════════════════════════════════════════
  FROST_LANCE: { id:'FROST_LANCE', name:'Frost Lance', type:'ICE', category:'PHYSICAL', power:75, accuracy:100, pp:15, priority:0, animStyle:'BEAM',
    effect:{type:'FREEZE_CHANCE',chance:10}, description:'A lance of ice hurled at the foe.' },
  SNOWSTORM: { id:'SNOWSTORM', name:'Snowstorm', type:'ICE', category:'SPECIAL', power:85, accuracy:90, pp:10, priority:0, animStyle:'VORTEX',
    effect:{type:'FREEZE_CHANCE',chance:20}, description:'A raging snowstorm blasts the foe.' },
  CRYO_BEAM: { id:'CRYO_BEAM', name:'Cryo Beam', type:'ICE', category:'SPECIAL', power:100, accuracy:90, pp:10, priority:0, animStyle:'BEAM',
    effect:{type:'FREEZE_CHANCE',chance:30}, description:'A beam of cryogenic energy may freeze the foe.' },
  SLEET_STORM: { id:'SLEET_STORM', name:'Sleet Storm', type:'ICE', category:'SPECIAL', power:65, accuracy:90, pp:15, priority:0, animStyle:'MULTI',
    effect:{type:'STAT_LOWER',stat:'spd',stages:1}, description:'Sleet pellets slow the foe.' },
  PERMAFROST_STRIKE: { id:'PERMAFROST_STRIKE', name:'Permafrost Strike', type:'ICE', category:'PHYSICAL', power:90, accuracy:95, pp:10, priority:0, animStyle:'SLAM',
    effect:{type:'STAT_LOWER',stat:'spd',stages:1}, description:'Freezes the ground beneath the foe on impact.' },
  BLIZZARD_BLADE: { id:'BLIZZARD_BLADE', name:'Blizzard Blade', type:'ICE', category:'PHYSICAL', power:80, accuracy:100, pp:10, priority:0, animStyle:'MELEE',
    effect:{type:'FREEZE_CHANCE',chance:20}, description:'A blade sharpened to arctic cold.' },
  ICE_SPIKE: { id:'ICE_SPIKE', name:'Ice Spike', type:'ICE', category:'PHYSICAL', power:50, accuracy:100, pp:25, priority:0, animStyle:'PROJECTILE',
    effect:{type:'FREEZE_CHANCE',chance:10}, description:'A sharp ice spike hurled at the foe.' },
  TUNDRA_WAVE: { id:'TUNDRA_WAVE', name:'Tundra Wave', type:'ICE', category:'SPECIAL', power:75, accuracy:100, pp:15, priority:0, animStyle:'WAVE',
    effect:{type:'FREEZE_CHANCE',chance:10}, description:'A wave of arctic air sweeps the battlefield.' },
  ABSOLUTE_ZERO: { id:'ABSOLUTE_ZERO', name:'Absolute Zero', type:'ICE', category:'SPECIAL', power:0, accuracy:30, pp:5, priority:0, animStyle:'BEAM',
    effect:{type:'ONE_HIT_KO'}, description:'Drops temperature to absolute zero. One-hit KO if it hits.' },
  AURORA_BLAST: { id:'AURORA_BLAST', name:'Aurora Blast', type:'ICE', category:'SPECIAL', power:80, accuracy:95, pp:10, priority:0, animStyle:'ARC',
    effect:{type:'FREEZE_CHANCE',chance:15}, description:'Northern lights solidify into a freezing blast.' },
  FROSTBITE: { id:'FROSTBITE', name:'Frostbite', type:'ICE', category:'STATUS', power:0, accuracy:100, pp:20, priority:0, animStyle:'FIELD',
    effect:{type:'FREEZE_CHANCE',chance:100}, description:'Inflicts frostbite, freezing the foe solid.' },
  POLAR_VORTEX: { id:'POLAR_VORTEX', name:'Polar Vortex', type:'ICE', category:'SPECIAL', power:110, accuracy:85, pp:8, priority:0, animStyle:'VORTEX',
    effect:{type:'FREEZE_CHANCE',chance:30}, description:'A devastating polar vortex engulfs the field.' },
  FROST_BREATH_CHILL: { id:'FROST_BREATH_CHILL', name:'Frost Breath', type:'ICE', category:'SPECIAL', power:60, accuracy:90, pp:15, priority:0, animStyle:'CONE',
    effect:{type:'FREEZE_CHANCE',chance:30}, description:'Critical-hit-always frosty breath chills the foe.' },
  ICE_WALL: { id:'ICE_WALL', name:'Ice Wall', type:'ICE', category:'STATUS', power:0, accuracy:100, pp:15, priority:0, animStyle:'SELF',
    effect:{type:'STAT_RAISE',stat:'def',stages:2}, description:'Erects a wall of thick ice to raise Defense.' },
  GLACIER_SMASH: { id:'GLACIER_SMASH', name:'Glacier Smash', type:'ICE', category:'PHYSICAL', power:100, accuracy:90, pp:10, priority:0, animStyle:'SLAM',
    effect:{type:'NONE'}, description:'Smashes the foe with a chunk of ancient glacier.' },
  HAILSTONE: { id:'HAILSTONE', name:'Hailstone', type:'ICE', category:'PHYSICAL', power:65, accuracy:100, pp:15, priority:0, animStyle:'PROJECTILE',
    effect:{type:'FLINCH',chance:20}, description:'A large hailstone may cause the foe to flinch.' },
  ARCTIC_WIND: { id:'ARCTIC_WIND', name:'Arctic Wind', type:'ICE', category:'SPECIAL', power:55, accuracy:95, pp:20, priority:0, animStyle:'WAVE',
    effect:{type:'STAT_LOWER',stat:'spd',stages:1}, description:'Freezing arctic winds slow the foe.' },
  SNOWFALL: { id:'SNOWFALL', name:'Snowfall', type:'ICE', category:'STATUS', power:0, accuracy:100, pp:20, priority:0, animStyle:'FIELD',
    effect:{type:'SET_WEATHER',weather:'SNOW'}, description:'Causes heavy snow to fall for 5 turns.' },
  CRYO_PUNCH: { id:'CRYO_PUNCH', name:'Cryo Punch', type:'ICE', category:'PHYSICAL', power:75, accuracy:100, pp:15, priority:0, animStyle:'MELEE',
    effect:{type:'FREEZE_CHANCE',chance:20}, description:'An icy punch that may freeze on contact.' },
  ICE_BEAM_BURST: { id:'ICE_BEAM_BURST', name:'Glacier Beam', type:'ICE', category:'SPECIAL', power:95, accuracy:100, pp:10, priority:0, animStyle:'BEAM',
    effect:{type:'FREEZE_CHANCE',chance:20}, description:'A condensed beam of glacier-cold energy.' },

  // ═══════════════════════════════════════════════════════
  // PHASE 2 BATCH A — NORMAL (20 new)
  // ═══════════════════════════════════════════════════════
  POWER_SLAM: { id:'POWER_SLAM', name:'Power Slam', type:'NORMAL', category:'PHYSICAL', power:85, accuracy:100, pp:10, priority:0, animStyle:'SLAM',
    effect:{type:'NONE'}, description:'A powerful slam attack with the user\'s full body.' },
  SHOCKWAVE_PULSE: { id:'SHOCKWAVE_PULSE', name:'Shockwave', type:'NORMAL', category:'SPECIAL', power:60, accuracy:100, pp:20, priority:0, animStyle:'PULSE',
    effect:{type:'NONE'}, description:'A pulse of raw kinetic energy that never misses.' },
  AERIAL_BLITZ: { id:'AERIAL_BLITZ', name:'Aerial Blitz', type:'NORMAL', category:'PHYSICAL', power:70, accuracy:100, pp:15, priority:1, animStyle:'ARC',
    effect:{type:'NONE'}, description:'A quick aerial charge that always strikes first.' },
  HORN_THRUST: { id:'HORN_THRUST', name:'Horn Thrust', type:'NORMAL', category:'PHYSICAL', power:0, accuracy:30, pp:5, priority:0, animStyle:'MELEE',
    effect:{type:'ONE_HIT_KO'}, description:'Drives a horn into the foe. One-hit KO if it hits.' },
  ECHO_STRIKE: { id:'ECHO_STRIKE', name:'Echo Strike', type:'NORMAL', category:'SPECIAL', power:60, accuracy:100, pp:20, priority:0, animStyle:'PULSE',
    effect:{type:'NONE'}, description:'An echoing strike whose power grows if used repeatedly.' },
  TAIL_SWEEP: { id:'TAIL_SWEEP', name:'Tail Sweep', type:'NORMAL', category:'PHYSICAL', power:55, accuracy:100, pp:20, priority:0, animStyle:'MELEE',
    effect:{type:'STAT_LOWER',stat:'spd',stages:1}, description:'Sweeps the foe\'s legs with the tail.' },
  CRUNCH_SMASH: { id:'CRUNCH_SMASH', name:'Crunch Smash', type:'NORMAL', category:'PHYSICAL', power:90, accuracy:95, pp:10, priority:0, animStyle:'SLAM',
    effect:{type:'FLINCH',chance:20}, description:'A bone-crunching impact may cause flinching.' },
  LAST_STAND: { id:'LAST_STAND', name:'Last Stand', type:'NORMAL', category:'PHYSICAL', power:200, accuracy:100, pp:5, priority:0, animStyle:'BURST',
    effect:{type:'RECOIL',fraction:50}, description:'Unleashes everything in a final desperate blow.' },
  GIGA_IMPACT_SURGE: { id:'GIGA_IMPACT_SURGE', name:'Giga Rush', type:'NORMAL', category:'PHYSICAL', power:110, accuracy:90, pp:10, priority:0, animStyle:'SLAM',
    effect:{type:'RECHARGE'}, description:'A massive rush attack that requires recharging.' },
  GROUND_POUND: { id:'GROUND_POUND', name:'Ground Pound', type:'NORMAL', category:'PHYSICAL', power:75, accuracy:100, pp:15, priority:0, animStyle:'SLAM',
    effect:{type:'FLINCH',chance:30}, description:'Pounds the ground with tremendous force.' },
  PRIMAL_ROAR: { id:'PRIMAL_ROAR', name:'Primal Roar', type:'NORMAL', category:'STATUS', power:0, accuracy:100, pp:20, priority:0, animStyle:'FIELD',
    effect:{type:'STAT_LOWER',stat:'atk',stages:1}, description:'A fearsome roar lowers the foe\'s Attack.' },
  CRUSH_CLAW: { id:'CRUSH_CLAW', name:'Crush Claw', type:'NORMAL', category:'PHYSICAL', power:75, accuracy:95, pp:10, priority:0, animStyle:'MELEE',
    effect:{type:'STAT_LOWER',stat:'def',stages:1}, description:'Crushing claws may lower the foe\'s Defense.' },
  FURY_SWIPES: { id:'FURY_SWIPES', name:'Fury Swipes', type:'NORMAL', category:'PHYSICAL', power:18, accuracy:80, pp:15, priority:0, animStyle:'MULTI',
    effect:{type:'MULTI_HIT',hits:'2-5'}, description:'Rakes with claws 2-5 times.' },
  DINO_DANCE: { id:'DINO_DANCE', name:'Dino Dance', type:'NORMAL', category:'STATUS', power:0, accuracy:100, pp:20, priority:0, animStyle:'SELF',
    effect:{type:'STAT_RAISE',stats:['atk','spd'],stages:1}, description:'A prehistoric dance raises Attack and Speed.' },
  BONE_CLUB: { id:'BONE_CLUB', name:'Bone Club', type:'NORMAL', category:'PHYSICAL', power:65, accuracy:85, pp:20, priority:0, animStyle:'SLAM',
    effect:{type:'FLINCH',chance:10}, description:'Bludgeons with a bone club. May cause flinching.' },
  MEGA_PUNCH: { id:'MEGA_PUNCH', name:'Mega Punch', type:'NORMAL', category:'PHYSICAL', power:80, accuracy:85, pp:20, priority:0, animStyle:'MELEE',
    effect:{type:'NONE'}, description:'A powerful punch thrown with full body weight.' },
  SHARP_STRIKE: { id:'SHARP_STRIKE', name:'Sharp Strike', type:'NORMAL', category:'PHYSICAL', power:70, accuracy:100, pp:15, priority:0, animStyle:'MELEE',
    effect:{type:'NONE'}, description:'A razor-precise strike that always deals solid damage.' },
  RAMPAGE: { id:'RAMPAGE', name:'Rampage', type:'NORMAL', category:'PHYSICAL', power:90, accuracy:100, pp:10, priority:0, animStyle:'SLAM',
    effect:{type:'CONFUSE',self:true}, description:'A rampaging attack that confuses the user.' },
  TRUMPETING: { id:'TRUMPETING', name:'Trumpeting', type:'NORMAL', category:'STATUS', power:0, accuracy:100, pp:15, priority:0, animStyle:'FIELD',
    effect:{type:'STAT_RAISE',stat:'atk',stages:1}, description:'A rallying call boosts the user\'s Attack.' },
  FOSSIL_STRIKE: { id:'FOSSIL_STRIKE', name:'Fossil Strike', type:'NORMAL', category:'PHYSICAL', power:95, accuracy:100, pp:10, priority:0, animStyle:'SLAM',
    effect:{type:'NONE'}, description:'Strikes with the force of ancient fossilized bone.' },

  // ═══════════════════════════════════════════════════════
  // PHASE 2 BATCH A — FIGHTING (20 new)
  // ═══════════════════════════════════════════════════════
  HURRICANE_KICK: { id:'HURRICANE_KICK', name:'Hurricane Kick', type:'FIGHTING', category:'PHYSICAL', power:85, accuracy:95, pp:10, priority:0, animStyle:'ARC',
    effect:{type:'NONE'}, description:'A spinning kick with tornado-like force.' },
  JAB_FLURRY: { id:'JAB_FLURRY', name:'Jab Flurry', type:'FIGHTING', category:'PHYSICAL', power:15, accuracy:100, pp:20, priority:0, animStyle:'MULTI',
    effect:{type:'MULTI_HIT',hits:'2-5'}, description:'A rapid flurry of jabs hits 2-5 times.' },
  POWER_UPPER: { id:'POWER_UPPER', name:'Power Upper', type:'FIGHTING', category:'PHYSICAL', power:90, accuracy:90, pp:10, priority:0, animStyle:'MELEE',
    effect:{type:'NONE'}, description:'A charged uppercut with devastating impact.' },
  GRAPPLE: { id:'GRAPPLE', name:'Grapple', type:'FIGHTING', category:'PHYSICAL', power:75, accuracy:100, pp:15, priority:0, animStyle:'MELEE',
    effect:{type:'STAT_LOWER',stat:'atk',stages:1}, description:'Grapples the foe, lowering its Attack.' },
  IRON_FIST: { id:'IRON_FIST', name:'Iron Fist', type:'FIGHTING', category:'PHYSICAL', power:80, accuracy:100, pp:10, priority:0, animStyle:'MELEE',
    effect:{type:'NONE'}, description:'A fist hardened like iron crashes into the foe.' },
  BODY_PRESS: { id:'BODY_PRESS', name:'Body Press', type:'FIGHTING', category:'PHYSICAL', power:80, accuracy:100, pp:10, priority:0, animStyle:'SLAM',
    effect:{type:'NONE'}, description:'Presses down with full body weight. Uses Defense for damage.' },
  MARTIAL_STRIKE: { id:'MARTIAL_STRIKE', name:'Martial Strike', type:'FIGHTING', category:'PHYSICAL', power:70, accuracy:100, pp:15, priority:0, animStyle:'MELEE',
    effect:{type:'FLINCH',chance:20}, description:'A disciplined martial arts strike.' },
  STOMP_RUSH: { id:'STOMP_RUSH', name:'Stomp Rush', type:'FIGHTING', category:'PHYSICAL', power:95, accuracy:95, pp:10, priority:0, animStyle:'SLAM',
    effect:{type:'NONE'}, description:'Charges and stomps with unstoppable momentum.' },
  POWER_TRIP: { id:'POWER_TRIP', name:'Power Trip', type:'FIGHTING', category:'PHYSICAL', power:20, accuracy:100, pp:10, priority:0, animStyle:'MELEE',
    effect:{type:'NONE'}, description:'Stronger when the user has raised many stats.' },
  TWIN_KICK: { id:'TWIN_KICK', name:'Twin Kick', type:'FIGHTING', category:'PHYSICAL', power:50, accuracy:100, pp:20, priority:0, animStyle:'MULTI',
    effect:{type:'MULTI_HIT',hits:2}, description:'Delivers two precise kicks in succession.' },
  BATTLE_CRY: { id:'BATTLE_CRY', name:'Battle Cry', type:'FIGHTING', category:'STATUS', power:0, accuracy:100, pp:15, priority:0, animStyle:'AURA',
    effect:{type:'STAT_RAISE',stats:['atk','def'],stages:1}, description:'A fierce battle cry raises Attack and Defense.' },
  GROUND_SLAM_FIGHT: { id:'GROUND_SLAM_FIGHT', name:'Impact Crash', type:'FIGHTING', category:'PHYSICAL', power:100, accuracy:90, pp:10, priority:0, animStyle:'SLAM',
    effect:{type:'FLINCH',chance:30}, description:'Crashes into the ground near the foe with flinch-inducing force.' },
  SPINNING_KICK: { id:'SPINNING_KICK', name:'Spinning Kick', type:'FIGHTING', category:'PHYSICAL', power:65, accuracy:100, pp:15, priority:0, animStyle:'ARC',
    effect:{type:'NONE'}, description:'A wide spinning kick hits multiple weak points.' },
  FOCUS_BLAST: { id:'FOCUS_BLAST', name:'Focus Blast', type:'FIGHTING', category:'SPECIAL', power:120, accuracy:70, pp:5, priority:0, animStyle:'BURST',
    effect:{type:'STAT_LOWER',stat:'spDef',stages:1}, description:'A focused blast of fighting energy.' },
  SLAM_DOWN_HARD: { id:'SLAM_DOWN_HARD', name:'Slam Down', type:'FIGHTING', category:'PHYSICAL', power:75, accuracy:100, pp:15, priority:0, animStyle:'SLAM',
    effect:{type:'NONE'}, description:'Slams the foe hard into the ground.' },
  PUMMEL: { id:'PUMMEL', name:'Pummel', type:'FIGHTING', category:'PHYSICAL', power:60, accuracy:100, pp:20, priority:0, animStyle:'MULTI',
    effect:{type:'MULTI_HIT',hits:'2-3'}, description:'Rapid punches batter the foe 2-3 times.' },
  BONE_BREAK: { id:'BONE_BREAK', name:'Bone Break', type:'FIGHTING', category:'PHYSICAL', power:85, accuracy:90, pp:10, priority:0, animStyle:'MELEE',
    effect:{type:'STAT_LOWER',stat:'def',stages:1}, description:'Strikes at weak points to lower Defense.' },
  LARIAT: { id:'LARIAT', name:'Lariat', type:'FIGHTING', category:'PHYSICAL', power:85, accuracy:100, pp:10, priority:0, animStyle:'MELEE',
    effect:{type:'NONE'}, description:'A powerful clothesline that ignores stat changes.' },
  SMASH_CHARGE: { id:'SMASH_CHARGE', name:'Smash Charge', type:'FIGHTING', category:'PHYSICAL', power:110, accuracy:90, pp:8, priority:0, animStyle:'SLAM',
    effect:{type:'STAT_LOWER',stat:'def',stages:1}, description:'Charges and smashes, lowering the foe\'s Defense.' },
  MARTIAL_ARTS: { id:'MARTIAL_ARTS', name:'Martial Arts', type:'FIGHTING', category:'STATUS', power:0, accuracy:100, pp:20, priority:0, animStyle:'SELF',
    effect:{type:'STAT_RAISE',stats:['atk','spd'],stages:1}, description:'Channels martial focus, raising Attack and Speed.' },

  // ═══════════════════════════════════════════════════════
  // PHASE 2 BATCH A — POISON (20 new)
  // ═══════════════════════════════════════════════════════
  VENOM_BURST: { id:'VENOM_BURST', name:'Venom Burst', type:'POISON', category:'SPECIAL', power:85, accuracy:95, pp:10, priority:0, animStyle:'BURST',
    effect:{type:'POISON_CHANCE',chance:30}, description:'A burst of concentrated venom splashes the foe.' },
  ACID_RAIN: { id:'ACID_RAIN', name:'Acid Rain', type:'POISON', category:'SPECIAL', power:70, accuracy:90, pp:15, priority:0, animStyle:'MULTI',
    effect:{type:'POISON_CHANCE',chance:20}, description:'Acidic rain drops hit 2-5 times, may poison.' },
  TOXIC_SLAM: { id:'TOXIC_SLAM', name:'Toxic Slam', type:'POISON', category:'PHYSICAL', power:80, accuracy:100, pp:10, priority:0, animStyle:'SLAM',
    effect:{type:'POISON_CHANCE',chance:30}, description:'Slams with a poison-coated body.' },
  MIASMA_CLOUD: { id:'MIASMA_CLOUD', name:'Miasma Cloud', type:'POISON', category:'STATUS', power:0, accuracy:90, pp:15, priority:0, animStyle:'FIELD',
    effect:{type:'POISON_CHANCE',chance:100}, description:'A cloud of miasma poisons the foe.' },
  NEUROTOXIN: { id:'NEUROTOXIN', name:'Neurotoxin', type:'POISON', category:'SPECIAL', power:75, accuracy:95, pp:15, priority:0, animStyle:'PULSE',
    effect:{type:'STAT_LOWER',stat:'spd',stages:1}, description:'Neurotoxins slow the foe\'s nervous system.' },
  CORROSIVE_SPIT: { id:'CORROSIVE_SPIT', name:'Corrosive Spit', type:'POISON', category:'SPECIAL', power:60, accuracy:100, pp:20, priority:0, animStyle:'PROJECTILE',
    effect:{type:'STAT_LOWER',stat:'def',stages:1}, description:'Corrosive spit eats away at armor.' },
  VENOM_STRIKE: { id:'VENOM_STRIKE', name:'Venom Strike', type:'POISON', category:'PHYSICAL', power:65, accuracy:100, pp:15, priority:0, animStyle:'MELEE',
    effect:{type:'POISON_CHANCE',chance:40}, description:'A venomous slash likely to poison.' },
  POISON_GAS: { id:'POISON_GAS', name:'Poison Gas', type:'POISON', category:'STATUS', power:0, accuracy:80, pp:20, priority:0, animStyle:'FIELD',
    effect:{type:'POISON_CHANCE',chance:100}, description:'Releases a cloud of noxious gas.' },
  ACID_DOWNPOUR: { id:'ACID_DOWNPOUR', name:'Acid Downpour', type:'POISON', category:'SPECIAL', power:100, accuracy:90, pp:10, priority:0, animStyle:'BURST',
    effect:{type:'POISON_CHANCE',chance:20}, description:'A torrential downpour of acid crashes down.' },
  PUTRID_WAVE: { id:'PUTRID_WAVE', name:'Putrid Wave', type:'POISON', category:'SPECIAL', power:75, accuracy:100, pp:15, priority:0, animStyle:'WAVE',
    effect:{type:'POISON_CHANCE',chance:30}, description:'A rotting wave of foul energy sweeps the field.' },
  TOXIC_CLAW: { id:'TOXIC_CLAW', name:'Toxic Claw', type:'POISON', category:'PHYSICAL', power:55, accuracy:100, pp:20, priority:0, animStyle:'MELEE',
    effect:{type:'POISON_CHANCE',chance:50}, description:'Claws coated in toxin likely to poison.' },
  SLUDGE_SURGE: { id:'SLUDGE_SURGE', name:'Sludge Surge', type:'POISON', category:'SPECIAL', power:80, accuracy:90, pp:10, priority:0, animStyle:'WAVE',
    effect:{type:'POISON_CHANCE',chance:30}, description:'A surge of toxic sludge washes over the foe.' },
  PLAGUE_BREATH: { id:'PLAGUE_BREATH', name:'Plague Breath', type:'POISON', category:'SPECIAL', power:70, accuracy:100, pp:15, priority:0, animStyle:'CONE',
    effect:{type:'POISON_CHANCE',chance:30}, description:'Plague-filled breath exhaled in a wide cone.' },
  VIPER_LUNGE: { id:'VIPER_LUNGE', name:'Viper Lunge', type:'POISON', category:'PHYSICAL', power:90, accuracy:95, pp:10, priority:0, animStyle:'MELEE',
    effect:{type:'POISON_CHANCE',chance:20}, description:'Lunges like a viper for a venomous bite.' },
  TOXIC_MIST: { id:'TOXIC_MIST', name:'Toxic Mist', type:'POISON', category:'STATUS', power:0, accuracy:100, pp:20, priority:0, animStyle:'FIELD',
    effect:{type:'STAT_LOWER',stat:'acc',stages:1}, description:'A mist of toxins obscures the foe\'s vision.' },
  CORROSION_PULSE: { id:'CORROSION_PULSE', name:'Corrosion Pulse', type:'POISON', category:'SPECIAL', power:65, accuracy:100, pp:15, priority:0, animStyle:'PULSE',
    effect:{type:'STAT_LOWER',stat:'def',stages:1}, description:'A pulse that corrodes the foe\'s defenses.' },
  VENOM_DRIP: { id:'VENOM_DRIP', name:'Venom Drip', type:'POISON', category:'SPECIAL', power:50, accuracy:100, pp:25, priority:0, animStyle:'PROJECTILE',
    effect:{type:'POISON_CHANCE',chance:40}, description:'Drips venom onto the foe. Likely to poison.' },
  TOXIC_SPINES: { id:'TOXIC_SPINES', name:'Toxic Spines', type:'POISON', category:'PHYSICAL', power:60, accuracy:95, pp:15, priority:0, animStyle:'MULTI',
    effect:{type:'POISON_CHANCE',chance:30}, description:'Fires toxic spines that may poison.' },
  NOXIOUS_CLOUD: { id:'NOXIOUS_CLOUD', name:'Noxious Cloud', type:'POISON', category:'SPECIAL', power:80, accuracy:90, pp:10, priority:0, animStyle:'VORTEX',
    effect:{type:'POISON_CHANCE',chance:50}, description:'A swirling noxious cloud heavily poisons the foe.' },
  VENOM_CANNON: { id:'VENOM_CANNON', name:'Venom Cannon', type:'POISON', category:'SPECIAL', power:110, accuracy:85, pp:8, priority:0, animStyle:'BEAM',
    effect:{type:'POISON_CHANCE',chance:20}, description:'Fires a concentrated beam of venom.' },

  // ═══════════════════════════════════════════════════════
  // PHASE 2 BATCH A — GROUND (20 new)
  // ═══════════════════════════════════════════════════════
  SAND_SURGE: { id:'SAND_SURGE', name:'Sand Surge', type:'GROUND', category:'SPECIAL', power:75, accuracy:100, pp:15, priority:0, animStyle:'WAVE',
    effect:{type:'STAT_LOWER',stat:'acc',stages:1}, description:'A surge of sand obscures the foe\'s vision.' },
  CAVE_IN: { id:'CAVE_IN', name:'Cave In', type:'GROUND', category:'PHYSICAL', power:100, accuracy:90, pp:10, priority:0, animStyle:'SLAM',
    effect:{type:'FLINCH',chance:30}, description:'Collapses the cave ceiling on the foe.' },
  MUD_WAVE: { id:'MUD_WAVE', name:'Mud Wave', type:'GROUND', category:'SPECIAL', power:70, accuracy:100, pp:15, priority:0, animStyle:'WAVE',
    effect:{type:'STAT_LOWER',stat:'acc',stages:1}, description:'A wave of thick mud splashes and obscures.' },
  EARTH_SLAM: { id:'EARTH_SLAM', name:'Earth Slam', type:'GROUND', category:'PHYSICAL', power:90, accuracy:95, pp:10, priority:0, animStyle:'SLAM',
    effect:{type:'NONE'}, description:'Slams with the full weight of the earth.' },
  DUST_STORM: { id:'DUST_STORM', name:'Dust Storm', type:'GROUND', category:'STATUS', power:0, accuracy:100, pp:15, priority:0, animStyle:'FIELD',
    effect:{type:'SET_WEATHER',weather:'SANDSTORM'}, description:'Stirs up a raging dust storm.' },
  SEISMIC_WAVE: { id:'SEISMIC_WAVE', name:'Seismic Wave', type:'GROUND', category:'SPECIAL', power:80, accuracy:95, pp:10, priority:0, animStyle:'WAVE',
    effect:{type:'FLINCH',chance:20}, description:'A seismic wave cracks the ground under the foe.' },
  QUICKSAND: { id:'QUICKSAND', name:'Quicksand', type:'GROUND', category:'STATUS', power:0, accuracy:90, pp:20, priority:0, animStyle:'FIELD',
    effect:{type:'PARALYSIS',chance:100}, description:'The foe sinks in quicksand, unable to move.' },
  BEDROCK_BASH: { id:'BEDROCK_BASH', name:'Bedrock Bash', type:'GROUND', category:'PHYSICAL', power:110, accuracy:90, pp:8, priority:0, animStyle:'SLAM',
    effect:{type:'NONE'}, description:'Smashes with a slab of pure bedrock.' },
  FOSSIL_QUAKE: { id:'FOSSIL_QUAKE', name:'Fossil Quake', type:'GROUND', category:'PHYSICAL', power:85, accuracy:100, pp:10, priority:0, animStyle:'BURST',
    effect:{type:'NONE'}, description:'Awakens fossilized energy deep within the earth.' },
  GRIT: { id:'GRIT', name:'Grit', type:'GROUND', category:'STATUS', power:0, accuracy:100, pp:15, priority:0, animStyle:'SELF',
    effect:{type:'STAT_RAISE',stats:['def','spDef'],stages:1}, description:'Channels gritty resilience to boost both defenses.' },
  ROCK_SLIDE_LOW: { id:'ROCK_SLIDE_LOW', name:'Ground Avalanche', type:'GROUND', category:'PHYSICAL', power:75, accuracy:90, pp:15, priority:0, animStyle:'WAVE',
    effect:{type:'FLINCH',chance:20}, description:'Debris slides toward the foe. May cause flinching.' },
  BURROW: { id:'BURROW', name:'Burrow', type:'GROUND', category:'PHYSICAL', power:80, accuracy:100, pp:10, priority:0, animStyle:'SLAM',
    effect:{type:'TWO_TURN'}, description:'Digs underground then strikes. Invulnerable on first turn.' },
  SAND_VEIL_ATTACK: { id:'SAND_VEIL_ATTACK', name:'Sand Veil', type:'GROUND', category:'STATUS', power:0, accuracy:100, pp:15, priority:0, animStyle:'SELF',
    effect:{type:'STAT_RAISE',stat:'spd',stages:1}, description:'Wraps in a sand veil that boosts Speed.' },
  GROUND_BURST: { id:'GROUND_BURST', name:'Ground Burst', type:'GROUND', category:'SPECIAL', power:90, accuracy:90, pp:10, priority:0, animStyle:'BURST',
    effect:{type:'NONE'}, description:'A geyser of earthen energy bursts upward.' },
  TERRAIN_SLASH: { id:'TERRAIN_SLASH', name:'Terrain Slash', type:'GROUND', category:'PHYSICAL', power:70, accuracy:100, pp:15, priority:0, animStyle:'MELEE',
    effect:{type:'NONE'}, description:'Slashes with a claw that tears up the terrain.' },
  MUDSLIDE: { id:'MUDSLIDE', name:'Mudslide', type:'GROUND', category:'PHYSICAL', power:80, accuracy:90, pp:10, priority:0, animStyle:'WAVE',
    effect:{type:'STAT_LOWER',stat:'spd',stages:1}, description:'A mudslide buries and slows the foe.' },
  CRUSHING_EARTH: { id:'CRUSHING_EARTH', name:'Crushing Earth', type:'GROUND', category:'PHYSICAL', power:100, accuracy:100, pp:10, priority:0, animStyle:'SLAM',
    effect:{type:'STAT_LOWER',stat:'def',stages:1}, description:'The earth compresses the foe, lowering Defense.' },
  FOSSIL_SMASH: { id:'FOSSIL_SMASH', name:'Fossil Smash', type:'GROUND', category:'PHYSICAL', power:80, accuracy:100, pp:15, priority:0, animStyle:'SLAM',
    effect:{type:'NONE'}, description:'Smashes with a prehistoric fossilized limb.' },
  CRATER_MAKER: { id:'CRATER_MAKER', name:'Crater Maker', type:'GROUND', category:'PHYSICAL', power:120, accuracy:85, pp:8, priority:0, animStyle:'SLAM',
    effect:{type:'RECOIL',fraction:25}, description:'Creates a crater on impact. Causes recoil.' },
  ANCIENT_QUAKE: { id:'ANCIENT_QUAKE', name:'Ancient Quake', type:'GROUND', category:'PHYSICAL', power:95, accuracy:90, pp:10, priority:0, animStyle:'BURST',
    effect:{type:'NONE'}, description:'Triggers dormant seismic energy from ancient times.' },

  // ═══════════════════════════════════════════════════════
  // PHASE 2 BATCH A — FLYING (20 new)
  // ═══════════════════════════════════════════════════════
  WIND_SLASH: { id:'WIND_SLASH', name:'Wind Slash', type:'FLYING', category:'PHYSICAL', power:70, accuracy:100, pp:15, priority:0, animStyle:'MELEE',
    effect:{type:'NONE'}, description:'A precise slash with a wind-sharpened wing.' },
  CYCLONE_DIVE: { id:'CYCLONE_DIVE', name:'Cyclone Dive', type:'FLYING', category:'PHYSICAL', power:90, accuracy:95, pp:10, priority:0, animStyle:'ARC',
    effect:{type:'NONE'}, description:'Spirals down in a cyclone to crash into the foe.' },
  FEATHER_BLADE: { id:'FEATHER_BLADE', name:'Feather Blade', type:'FLYING', category:'PHYSICAL', power:55, accuracy:100, pp:20, priority:0, animStyle:'MULTI',
    effect:{type:'MULTI_HIT',hits:'2-5'}, description:'Razor feathers strike 2-5 times.' },
  SKY_FURY: { id:'SKY_FURY', name:'Sky Fury', type:'FLYING', category:'PHYSICAL', power:100, accuracy:90, pp:10, priority:0, animStyle:'SLAM',
    effect:{type:'NONE'}, description:'Crashes from the sky with furious speed.' },
  TAILWIND_BOOST: { id:'TAILWIND_BOOST', name:'Tailwind Boost', type:'FLYING', category:'STATUS', power:0, accuracy:100, pp:15, priority:0, animStyle:'SELF',
    effect:{type:'STAT_RAISE',stat:'spd',stages:2}, description:'Riding the tailwind sharply boosts Speed.' },
  GUST_SLICE: { id:'GUST_SLICE', name:'Gust Slice', type:'FLYING', category:'SPECIAL', power:60, accuracy:100, pp:20, priority:0, animStyle:'ARC',
    effect:{type:'NONE'}, description:'A slice of focused wind cuts through the foe.' },
  WING_STORM: { id:'WING_STORM', name:'Wing Storm', type:'FLYING', category:'PHYSICAL', power:85, accuracy:95, pp:10, priority:0, animStyle:'VORTEX',
    effect:{type:'NONE'}, description:'Beats wings into a storm that pounds the foe.' },
  UPDRAFT: { id:'UPDRAFT', name:'Updraft', type:'FLYING', category:'STATUS', power:0, accuracy:100, pp:20, priority:0, animStyle:'SELF',
    effect:{type:'STAT_RAISE',stats:['def','spd'],stages:1}, description:'An updraft raises Defense and Speed.' },
  DIVE_BOMB: { id:'DIVE_BOMB', name:'Dive Bomb', type:'FLYING', category:'PHYSICAL', power:110, accuracy:90, pp:8, priority:0, animStyle:'SLAM',
    effect:{type:'FLINCH',chance:30}, description:'Drops from altitude to bomb the foe below.' },
  RAZOR_WIND_STRIKE: { id:'RAZOR_WIND_STRIKE', name:'Razor Wind', type:'FLYING', category:'SPECIAL', power:80, accuracy:100, pp:10, priority:0, animStyle:'ARC',
    effect:{type:'TWO_TURN'}, description:'Builds then releases razor-edged wind blades.' },
  GLIDE_STRIKE: { id:'GLIDE_STRIKE', name:'Glide Strike', type:'FLYING', category:'PHYSICAL', power:65, accuracy:100, pp:20, priority:1, animStyle:'ARC',
    effect:{type:'NONE'}, description:'Glides in fast for a quick hit.' },
  PTEROSAUR_DIVE: { id:'PTEROSAUR_DIVE', name:'Ptero Dive', type:'FLYING', category:'PHYSICAL', power:95, accuracy:95, pp:10, priority:0, animStyle:'ARC',
    effect:{type:'NONE'}, description:'A pterosaur-speed diving strike.' },
  SKY_BEAM: { id:'SKY_BEAM', name:'Sky Beam', type:'FLYING', category:'SPECIAL', power:80, accuracy:100, pp:10, priority:0, animStyle:'BEAM',
    effect:{type:'NONE'}, description:'A beam of concentrated wind energy from above.' },
  WIND_VEIL: { id:'WIND_VEIL', name:'Wind Veil', type:'FLYING', category:'STATUS', power:0, accuracy:100, pp:20, priority:0, animStyle:'SELF',
    effect:{type:'STAT_RAISE',stat:'def',stages:1}, description:'Wraps in circling winds that bolster Defense.' },
  TEMPEST_STRIKE: { id:'TEMPEST_STRIKE', name:'Tempest Strike', type:'FLYING', category:'SPECIAL', power:90, accuracy:90, pp:10, priority:0, animStyle:'BURST',
    effect:{type:'PARALYSIS',chance:20}, description:'The tempest\'s force may paralyze the foe.' },
  SOAR: { id:'SOAR', name:'Soar', type:'FLYING', category:'STATUS', power:0, accuracy:100, pp:15, priority:0, animStyle:'SELF',
    effect:{type:'STAT_RAISE',stats:['atk','spd'],stages:1}, description:'Soars to great height, boosting Attack and Speed.' },
  TYPHOON: { id:'TYPHOON', name:'Typhoon', type:'FLYING', category:'SPECIAL', power:110, accuracy:85, pp:8, priority:0, animStyle:'VORTEX',
    effect:{type:'NONE'}, description:'Summons a full typhoon against the foe.' },
  AERIAL_VOLLEY: { id:'AERIAL_VOLLEY', name:'Aerial Volley', type:'FLYING', category:'PHYSICAL', power:50, accuracy:100, pp:20, priority:0, animStyle:'MULTI',
    effect:{type:'MULTI_HIT',hits:'2-5'}, description:'A volley of aerial strikes hits 2-5 times.' },
  FEATHER_DANCE_ATK: { id:'FEATHER_DANCE_ATK', name:'Feather Blade Dance', type:'FLYING', category:'PHYSICAL', power:75, accuracy:100, pp:15, priority:0, animStyle:'MELEE',
    effect:{type:'STAT_LOWER',stat:'atk',stages:1}, description:'Dances with bladed feathers, lowering foe\'s Attack.' },
  CLOUD_BURST: { id:'CLOUD_BURST', name:'Cloud Burst', type:'FLYING', category:'SPECIAL', power:75, accuracy:100, pp:15, priority:0, animStyle:'BURST',
    effect:{type:'NONE'}, description:'Condenses clouds into a burst of aerial energy.' },
`;

// Filter out existing IDs
const blocks = newMoves.split(/\n  (?=[A-Z_0-9]+:\s*\{)/).filter(b => {
  const m = b.match(/^([A-Z_0-9]+):/);
  return m && !existing.has(m[1]);
});

console.log('New moves to add:', blocks.length);

// Find insertion point (before closing };)
const insertPos = src.lastIndexOf('\n};');
if (insertPos === -1) { console.error('Could not find insertion point'); process.exit(1); }

const toInsert = '\n' + blocks.join('\n  ') + '\n';
const newSrc = src.slice(0, insertPos) + toInsert + src.slice(insertPos);

fs.writeFileSync('./js/data/moves.js', newSrc, 'utf8');
console.log('Done! moves.js updated.');
